isolatedNixBuilds:
  - canvas

packageExtensions:
  fetchache@*:
    dependencies:
      "@types/http-cache-semantics": "*"

plugins:
  - checksum: 4ae37aa0a6a0d226889f66fb2f7482e321b0c82b8fa8ed2110d8cdfbd482c87542050ded54cb08bf473e4245ef0160668c689c93848416499a975d876a1e18b1
    path: .yarn/plugins/yarn-plugin-nixify.cjs
    spec: "https://raw.githubusercontent.com/stephank/yarn-plugin-nixify/main/dist/yarn-plugin-nixify.js"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
  os:
    - darwin
    - linux
