isolatedNixBuilds:
  - canvas

packageExtensions:
  fetchache@*:
    dependencies:
      "@types/http-cache-semantics": "*"

plugins:
  - checksum: 71f925df66e6f5dadfbbf231cf2a72bf9a16a53506763e6228d3d909f6b025560fb38723665246c9855ea7770b97fb324337a5c7643d18709707820dd60d7931
    path: .yarn/plugins/yarn-plugin-nixify.cjs
    spec: "https://raw.githubusercontent.com/stephank/yarn-plugin-nixify/main/dist/yarn-plugin-nixify.js"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
  os:
    - darwin
    - linux
