# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

{ lib, stdenv, nodejs, git, cacert, fetchurl, writeShellScript, writeShellScriptBin }:
{ src, overrideAttrs ? null, ... } @ args:

let

  cacheFolder = ".yarn/cache";
  lockfile = ./yarn.lock;

  # Call overrideAttrs on a derivation if a function is provided.
  optionalOverride = fn: drv:
    if fn == null then drv else drv.overrideAttrs fn;

  # Simple stub that provides the global yarn command.
  yarn = writeShellScriptBin "yarn" ''
    exec '${nodejs}/bin/node' '${./.yarn/releases/yarn-3.4.1.cjs}' "$@"
  '';

  # Common attributes between Yarn derivations.
  drvCommon = {
    # Make sure the build uses the right Node.js version everywhere.
    buildInputs = [ nodejs yarn ];
    # Tell node-gyp to use the provided Node.js headers for native code builds.
    npm_config_nodedir = nodejs;
  };

  # Comman variables that we set in a Nix build, but not in a Nix shell.
  buildVars = ''
    # Make Yarn produce friendlier logging for automated builds.
    export CI=1
    # Tell node-pre-gyp to never fetch binaries / always build from source.
    export npm_config_build_from_source=true
    # Disable Nixify plugin to save on some unnecessary processing.
    export yarn_enable_nixify=false
  '';

  # Create derivations for fetching dependencies.
  cacheDrvs = let
    builder = writeShellScript "yarn-cache-builder" ''
      source $stdenv/setup
      cd "$src"
      ${buildVars}
      HOME="$TMP" yarn_cache_folder="$TMP" \
        yarn nixify fetch-one $locator
      # Because we change the cache dir, Yarn may generate a different name.
      mv "$TMP/$(sed 's/-[^-]*\.[^-]*$//' <<< "$outputFilename")"-* $out
    '';
  in lib.mapAttrs (locator: { filename, sha512 }: stdenv.mkDerivation {
    inherit src builder locator;
    name = lib.strings.sanitizeDerivationName locator;
    buildInputs = [ yarn git cacert ];
    outputFilename = filename;
    outputHashMode = "flat";
    outputHashAlgo = "sha512";
    outputHash = sha512;
  }) cacheEntries;

  # Create a shell snippet to copy dependencies from a list of derivations.
  mkCacheBuilderForDrvs = drvs:
    writeShellScript "collect-yarn-cache" (lib.concatMapStrings (drv: ''
      cp ${drv} '${drv.outputFilename}'
    '') drvs);

  # Create a shell snippet to copy dependencies from a list of locators.
  mkCacheBuilderForLocators = let
    pickCacheDrvs = map (locator: cacheDrvs.${locator});
  in locators:
    mkCacheBuilderForDrvs (pickCacheDrvs locators);

  # Create a derivation that builds a node-pre-gyp module in isolation.
  mkIsolatedBuild = { pname, version, reference, locators }: stdenv.mkDerivation (drvCommon // {
    inherit pname version;
    dontUnpack = true;

    configurePhase = ''
      ${buildVars}
      unset yarn_enable_nixify # plugin is not present
    '';

    buildPhase = ''
      mkdir -p .yarn/cache
      pushd .yarn/cache > /dev/null
      source ${mkCacheBuilderForLocators locators}
      popd > /dev/null

      echo '{ "dependencies": { "${pname}": "${reference}" } }' > package.json
      install -m 0600 ${lockfile} ./yarn.lock
      export yarn_global_folder="$TMP"
      export YARN_ENABLE_IMMUTABLE_INSTALLS=false
      yarn --immutable-cache
    '';

    installPhase = ''
      unplugged=( .yarn/unplugged/${pname}-*/node_modules/* )
      if [[ ! -e "''${unplugged[@]}" ]]; then
        echo >&2 "Could not find the unplugged path for ${pname}"
        exit 1
      fi

      mv "$unplugged" $out
    '';
  });

  # Main project derivation.
  project = stdenv.mkDerivation (drvCommon // {
    inherit src;
    name = "castlingclub";

    configurePhase = ''
      ${buildVars}

      # Copy over the Yarn cache.
      rm -fr '${cacheFolder}'
      mkdir -p '${cacheFolder}'
      pushd '${cacheFolder}' > /dev/null
      source ${mkCacheBuilderForDrvs (lib.attrValues cacheDrvs)}
      popd > /dev/null

      # Yarn may need a writable home directory.
      export yarn_global_folder="$TMP"

      # Some node-gyp calls may call out to npm, which could fail due to an
      # read-only home dir.
      export HOME="$TMP"

      # running preConfigure after the cache is populated allows for
      # preConfigure to contain substituteInPlace for dependencies as well as the
      # main project. This is necessary for native bindings that maybe have
      # hardcoded values.
      runHook preConfigure

      # Copy in isolated builds.
      echo 'injecting build for canvas'
      yarn nixify inject-build \
        "canvas@npm:2.11.0" \
        ${isolated."canvas@npm:2.11.0"} \
        ".yarn/unplugged/canvas-npm-2.11.0-1643476467/node_modules/canvas"
      echo 'running yarn install'

      # Run normal Yarn install to complete dependency installation.
      yarn install --immutable --immutable-cache

      runHook postConfigure
    '';

    buildPhase = ''
      runHook preBuild
      runHook postBuild
    '';

    installPhase = ''
      runHook preInstall

      # Move the package contents to the output directory.
      if grep -q '"workspaces"' package.json; then
        # We can't use `yarn pack` in a workspace setup, because it only
        # packages the outer workspace.
        mkdir -p "$out/libexec"
        mv $PWD "$out/libexec/$name"
      else
        # - If the package.json has a `files` field, only files matching those patterns are copied
        # - Otherwise all files are copied.
        yarn pack --out package.tgz
        mkdir -p "$out/libexec/$name"
        tar xzvf package.tgz --directory "$out/libexec/$name" --strip-components=1

        cp .yarnrc* ${lockfile} "$out/libexec/$name"
        cp --recursive .yarn "$out/libexec/$name"

        # If the project uses the node-modules linker, then
        # include the node_modules folder in the package.
        if [ -d node_modules ]; then
          cp --recursive node_modules "$out/libexec/$name"
        else
          # Otherwise, assume PnP. Copy the loader into the package.
          cp .pnp.* "$out/libexec/$name"
        fi
      fi

      cd "$out/libexec/$name"

      # Invoke a plugin internal command to setup binaries.
      mkdir -p "$out/bin"
      yarn nixify install-bin $out/bin

      # A package with node_modules doesn't need the cache
      if [ -d node_modules ]; then
        yarn cache clean
      fi

      runHook postInstall
    '';

    passthru = {
      inherit nodejs;
      yarn-freestanding = yarn;
      yarn = writeShellScriptBin "yarn" ''
        exec '${yarn}/bin/yarn' --cwd '${overriddenProject}/libexec/${overriddenProject.name}' "$@"
      '';
    };
  });

  overriddenProject = optionalOverride overrideAttrs project;

cacheEntries = {
"@digitalbazaar/http-client@npm:3.3.0" = { filename = "@digitalbazaar-http-client-npm-3.3.0-5a9c586679-95566bdb39.zip"; sha512 = "95566bdb391ecb29f949a9553d0b3ddf1b574f63581f9028c8dd5e0ade7961a970eeeb0e4be0ef39ab577aff118a2b564fed41924c7130ef9d137807c44d1783"; };
"@gar/promisify@npm:1.1.3" = { filename = "@gar-promisify-npm-1.1.3-ac1a325862-4059f790e2.zip"; sha512 = "4059f790e2d07bf3c3ff3e0fec0daa8144fe35c1f6e0111c9921bd32106adaa97a4ab096ad7dab1e28ee6a9060083c4d1a4ada42a7f5f3f7a96b8812e2b757c1"; };
"@koa/router@npm:10.1.1" = { filename = "@koa-router-npm-10.1.1-a2816a45c1-3475f42355.zip"; sha512 = "3475f4235576d24eaa218d55e845fb81946288d65b87aa8aeda1a23b11b5556a02b9a8ff1ea520bb988ec7201523c41cff5abce9285fd12b9e839d7590cd2ce1"; };
"@mapbox/node-pre-gyp@npm:1.0.10" = { filename = "@mapbox-node-pre-gyp-npm-1.0.10-1811160047-1a98db05d9.zip"; sha512 = "1a98db05d955b74dad3814679593df293b9194853698f3f5f1ed00ecd93128cdd4b14fb8767fe44ac6981ef05c23effcfdc88710e7c1de99ccb6f647890597c8"; };
"@npmcli/fs@npm:2.1.2" = { filename = "@npmcli-fs-npm-2.1.2-08d434e77b-405074965e.zip"; sha512 = "405074965e72d4c9d728931b64d2d38e6ea12066d4fad651ac253d175e413c06fe4350970c783db0d749181da8fe49c42d3880bd1cbc12cd68e3a7964d820225"; };
"@npmcli/move-file@npm:2.0.1" = { filename = "@npmcli-move-file-npm-2.0.1-b593d8f741-52dc02259d.zip"; sha512 = "52dc02259d98da517fae4cb3a0a3850227bdae4939dda1980b788a7670636ca2b4a01b58df03dd5f65c1e3cb70c50fa8ce5762b582b3f499ec30ee5ce1fd9380"; };
"@rdfjs/data-model@npm:1.3.4" = { filename = "@rdfjs-data-model-npm-1.3.4-65acf42a87-88a5f8c436.zip"; sha512 = "88a5f8c4364291728728ef8a5e85733c55e61afe70d6f776417f3cfeaa8283c4d95234df993040890e51645022eef1fa457b1cdecbe597360bbb84eacf2a62aa"; };
"@rdfjs/types@npm:1.1.0" = { filename = "@rdfjs-types-npm-1.1.0-a00e1e81cf-68fad6328a.zip"; sha512 = "68fad6328a0115158a83abb01890997e8d90538ddd6db32530dc19e2761c28cce0a503b1f1506670bc98eff16fd20e542c6fb203adf37912eb9dc616766e677e"; };
"@sindresorhus/is@npm:5.3.0" = { filename = "@sindresorhus-is-npm-5.3.0-9deec66459-b31cebabcd.zip"; sha512 = "b31cebabcdece3d5322de2a4dbc8c0f004e04147a00f2606787bcaf5655ad4b1954f6727fc6914c524009b2b9a2cc01c42835b55f651ce69fd2a0083b60bb852"; };
"@szmarczak/http-timer@npm:5.0.1" = { filename = "@szmarczak-http-timer-npm-5.0.1-52261e5986-fc9cb993e8.zip"; sha512 = "fc9cb993e808806692e4a3337c90ece0ec00c89f4b67e3652a356b89730da98bc824273a6d67ca84d5f33cd85f317dcd5ce39d8cc0a2f060145a608a7cb8ce92"; };
"@tootallnate/once@npm:2.0.0" = { filename = "@tootallnate-once-npm-2.0.0-e36cf4f140-ad87447820.zip"; sha512 = "ad87447820dd3f24825d2d947ebc03072b20a42bfc96cbafec16bff8bbda6c1a81fcb0be56d5b21968560c5359a0af4038a68ba150c3e1694fe4c109a063bed8"; };
"@types/accepts@npm:1.3.5" = { filename = "@types-accepts-npm-1.3.5-1d59cd2a7a-590b758057.zip"; sha512 = "590b7580570534a640510c071e09074cf63b5958b237a728f94322567350aea4d239f8a9d897a12b15c856b992ee4d7907e9812bb079886af2c00714e7fb3f60"; };
"@types/body-parser@npm:1.19.2" = { filename = "@types-body-parser-npm-1.19.2-f845b7b538-e17840c7d7.zip"; sha512 = "e17840c7d747a549f00aebe72c89313d09fbc4b632b949b2470c5cb3b1cb73863901ae84d9335b567a79ec5efcfb8a28ff8e3f36bc8748a9686756b6d5681f40"; };
"@types/chai@npm:4.3.4" = { filename = "@types-chai-npm-4.3.4-fc230290e8-571184967b.zip"; sha512 = "571184967beb03bf64c4392a13a7d44e72da9af5a1e83077ff81c39cf59c0fda2a5c78d2005084601cf8f3d11726608574d8b5b4a0e3e9736792807afd926cd0"; };
"@types/co-body@npm:6.1.0" = { filename = "@types-co-body-npm-6.1.0-9c84c63ec0-95de9fe423.zip"; sha512 = "95de9fe423b3f081e849a51905a8d3346b4e6147efd27b10aadf14c5a1b9f3f2c6e50f0175ac3734be5213b8f41f9a7dda651ee13db9f4d93810408e01ff0432"; };
"@types/connect@npm:3.4.35" = { filename = "@types-connect-npm-3.4.35-7337eee0a3-fe81351470.zip"; sha512 = "fe81351470f2d3165e8b12ce33542eef89ea893e36dd62e8f7d72566dfb7e448376ae962f9f3ea888547ce8b55a40020ca0e01d637fab5d99567673084542641"; };
"@types/content-disposition@npm:0.5.5" = { filename = "@types-content-disposition-npm-0.5.5-2219aba782-fdf7379db1.zip"; sha512 = "fdf7379db1d509990bcf9a21d85f05aad878596f28b1418f9179f6436cb22513262c670ce88c6055054a7f5804a9303eeacb70aa59a5e11ffdc1434559db9692"; };
"@types/cookies@npm:0.7.7" = { filename = "@types-cookies-npm-0.7.7-0fbdd53be5-d3759efc11.zip"; sha512 = "d3759efc1182cb0651808570ae13638677b67b0ea724eef7b174e58ffe6ea044b62c7c2715e532f76f88fce4dd8101ed32ac6fbb73226db654017924e8a2a1e6"; };
"@types/debug@npm:4.1.7" = { filename = "@types-debug-npm-4.1.7-f54c81f8db-0a7b89d8ed.zip"; sha512 = "0a7b89d8ed72526858f0b61c6fd81f477853e8c4415bb97f48b1b5545248d2ae389931680b94b393b993a7cfe893537a200647d93defe6d87159b96812305adc"; };
"@types/ejs@npm:3.1.1" = { filename = "@types-ejs-npm-3.1.1-0ab41f0e19-12fa444920.zip"; sha512 = "12fa444920aaa70af2fae4424fa62b49c23b31a37129c428b7c9f9068e58c0696b4e5601b0449f87bae8794e039c679a43651c356c34f17d1bb460456dd41441"; };
"@types/express-serve-static-core@npm:4.17.33" = { filename = "@types-express-serve-static-core-npm-4.17.33-0366bd5654-dce580d16b.zip"; sha512 = "dce580d16b85f207445af9d4053d66942b27d0c72e86153089fa00feee3e96ae336b7bedb31ed4eea9e553c99d6dd356ed6e0928f135375d9f862a1a8015adf2"; };
"@types/express@npm:4.17.17" = { filename = "@types-express-npm-4.17.17-46fe8173db-0196dacc27.zip"; sha512 = "0196dacc275ac3ce89d7364885cb08e7fb61f53ca101f65886dbf1daf9b7eb05c0943e2e4bbd01b0cc5e50f37e0eea7e4cbe97d0304094411ac73e1b7998f4da"; };
"@types/http-assert@npm:1.5.3" = { filename = "@types-http-assert-npm-1.5.3-d45bf58309-9553e5a0b8.zip"; sha512 = "9553e5a0b8bcfdac4b51d3fa3b89a91b5450171861a667a5b4c47204e0f4a1ca865d97396e6ceaf220e87b64d06b7a8bad7bfba15ef97acb41a87507c9940dbc"; };
"@types/http-cache-semantics@npm:4.0.1" = { filename = "@types-http-cache-semantics-npm-4.0.1-90863c7a3e-1048aacf62.zip"; sha512 = "1048aacf627829f0d5f00184e16548205cd9f964bf0841c29b36bc504509230c40bc57c39778703a1c965a6f5b416ae2cbf4c1d4589c889d2838dd9dbfccf6e9"; };
"@types/http-errors@npm:1.8.2" = { filename = "@types-http-errors-npm-1.8.2-1208ef5c6d-ecc365eea9.zip"; sha512 = "ecc365eea98d7eca650d593e742571acc3003742f0dd0fbbb15b8fce286e0f7421644b4140fb9bf701bbb7f1b744aea3967ebe025f0f0811aa5ab2c3d40fe111"; };
"@types/http-errors@npm:2.0.1" = { filename = "@types-http-errors-npm-2.0.1-c59d5079a7-3bb0c50b0a.zip"; sha512 = "3bb0c50b0a652e679a84c30cd0340d696c32ef6558518268c238840346c077f899315daaf1c26c09c57ddd5dc80510f2a7f46acd52bf949e339e35ed3ee9654f"; };
"@types/keygrip@npm:1.0.2" = { filename = "@types-keygrip-npm-1.0.2-2e57be51bc-60bc2738a4.zip"; sha512 = "60bc2738a4f107070ee3d96f44709cb38f3a96c7ccabab09f56c1b2b4d85f869fd8fb9f1f2937e863d0e9e781f005c2223b823bf32b859185b4f52370c352669"; };
"@types/keyv@npm:3.1.4" = { filename = "@types-keyv-npm-3.1.4-a8082ea56b-e009a2bfb5.zip"; sha512 = "e009a2bfb50e90ca9b7c6e8f648f8464067271fd99116f881073fa6fa76dc8d0133181dd65e6614d5fb1220d671d67b0124aef7d97dc02d7e342ab143a47779d"; };
"@types/koa-compose@npm:3.2.5" = { filename = "@types-koa-compose-npm-3.2.5-b9ab25d904-5d1147c4b0.zip"; sha512 = "5d1147c4b057eb158195f442f0384f06503f3e69dba99fb517b30a05261a9f92928945c12bb1cfc17a5b7d60db003f38b455a3a9b125f12e4fc81fffa396b3cf"; };
"@types/koa@npm:2.13.5" = { filename = "@types-koa-npm-2.13.5-ee6d93204c-e3b634d934.zip"; sha512 = "e3b634d934b79ce8f394bf4130511596081f9c073dbfb4309aa32e4c421c47049a002b65111f8d9687eabec55d5a27b1b9ae0699afa83894cb7032c3536bfa17"; };
"@types/koa__router@npm:12.0.0" = { filename = "@types-koa__router-npm-12.0.0-eacee91aaa-ebfee772f7.zip"; sha512 = "ebfee772f7a9c5ff5e296a24443eb2c288fa2e5b8c60afbb460b41f0bd0d68c8a722fff5984eef7b7d90d057fe6f556171695ea83e2cdbeef3e2462f73c362b7"; };
"@types/mime@npm:3.0.1" = { filename = "@types-mime-npm-3.0.1-dec03536dc-4040fac73f.zip"; sha512 = "4040fac73fd0cea2460e29b348c1a6173da747f3a87da0dbce80dd7a9355a3d0e51d6d9a401654f3e5550620e3718b5a899b2ec1debf18424e298a2c605346e7"; };
"@types/mocha@npm:10.0.1" = { filename = "@types-mocha-npm-10.0.1-7c94e9e170-224ea9fce7.zip"; sha512 = "224ea9fce7b1734ccdb9aa99a622d902a538ce1847bca7fd22c5fb38adcf3ed536f50f48f587085db988a4bb3c2eb68f4b98e1cd6a38bc5547bd3bbbedc54495"; };
"@types/ms@npm:0.7.31" = { filename = "@types-ms-npm-0.7.31-ea3b89342b-daadd354ae.zip"; sha512 = "daadd354aedde024cce6f5aa873fefe7b71b22cd0e28632a69e8b677aeb48ae8caa1c60e5919bb781df040d116b01cb4316335167a3fc0ef6a63fa3614c0f6da"; };
"@types/node@npm:18.13.0" = { filename = "@types-node-npm-18.13.0-00f732af8e-4ea10f8802.zip"; sha512 = "4ea10f8802848b01672bce938f678b6774ca2cee0c9774f12275ab064ae07818419c3e2e41d6257ce7ba846d1ea26c63214aa1dfa4166fa3746291752b8c6416"; };
"@types/pg@npm:8.6.6" = { filename = "@types-pg-npm-8.6.6-a6578d0c17-ac145553a8.zip"; sha512 = "ac145553a8ad2f357feacad1bceaf5d6ce904eb9d66233b84c469a2b4fa3738d4ebdf29b7ea45387be2d07f915fd873a229f90a2f766d7c377afa7c41fbcf8d1"; };
"@types/qs@npm:6.9.7" = { filename = "@types-qs-npm-6.9.7-4a3e6ca0d0-7fd6f9c250.zip"; sha512 = "7fd6f9c25053e9b5bb6bc9f9f76c1d89e6c04f7707a7ba0e44cc01f17ef5284adb82f230f542c2d5557d69407c9a40f0f3515e8319afd14e1e16b5543ac6cdba"; };
"@types/range-parser@npm:1.2.4" = { filename = "@types-range-parser-npm-1.2.4-23d797fbde-b7c0dfd508.zip"; sha512 = "b7c0dfd5080a989d6c8bb0b6750fc0933d9acabeb476da6fe71d8bdf1ab65e37c136169d84148034802f48378ab94e3c37bb4ef7656b2bec2cb9c0f8d4146a95"; };
"@types/rdf-js@npm:4.0.1" = { filename = "@types-rdf-js-npm-4.0.1-d7342ebf4f-a2319591d4.zip"; sha512 = "a2319591d43cfcbeae77f4f02c3a8143cd7b224fd8a1d5d932867b0d53106815d39187d7b613e292d8d1fc97ce5936b82975a0244eb910583ad768b345b13d19"; };
"@types/serve-static@npm:1.15.0" = { filename = "@types-serve-static-npm-1.15.0-ec80a4ac87-b6ac93d471.zip"; sha512 = "b6ac93d471fb0f53ddcac1f9b67572a09cd62806f7db5855244b28f6f421139626f24799392566e97d1ffc61b12f9de7f30380c39fcae3c8a161fe161d44edf2"; };
"@types/uuid@npm:8.3.4" = { filename = "@types-uuid-npm-8.3.4-7547f4402c-6f11f3ff70.zip"; sha512 = "6f11f3ff70f30210edaa8071422d405e9c1d4e53abbe50fdce365150d3c698fe7bbff65c1e71ae080cbfb8fded860dbb5e174da96fdbbdfcaa3fb3daa474d20f"; };
"abbrev@npm:1.1.1" = { filename = "abbrev-npm-1.1.1-3659247eab-a4a97ec07d.zip"; sha512 = "a4a97ec07d7ea112c517036882b2ac22f3109b7b19077dc656316d07d308438aac28e4d9746dc4d84bf6b1e75b4a7b0a5f3cb30592419f128ca9a8cee3bcfa17"; };
"abort-controller@npm:3.0.0" = { filename = "abort-controller-npm-3.0.0-2f3a9a2bcb-170bdba9b4.zip"; sha512 = "170bdba9b47b7e65906a28c8ce4f38a7a369d78e2271706f020849c1bfe0ee2067d4261df8bbb66eb84f79208fd5b710df759d64191db58cfba7ce8ef9c54b75"; };
"accepts@npm:1.3.8" = { filename = "accepts-npm-1.3.8-9a812371c9-50c43d32e7.zip"; sha512 = "50c43d32e7b50285ebe84b613ee4a3aa426715a7d131b65b786e2ead0fd76b6b60091b9916d3478a75f11f162628a2139991b6c03ab3f1d9ab7c86075dc8eab4"; };
"agent-base@npm:6.0.2" = { filename = "agent-base-npm-6.0.2-428f325a93-f52b6872cc.zip"; sha512 = "f52b6872cc96fd5f622071b71ef200e01c7c4c454ee68bc9accca90c98cfb39f2810e3e9aa330435835eedc8c23f4f8a15267f67c6e245d2b33757575bdac49d"; };
"agentkeepalive@npm:4.2.1" = { filename = "agentkeepalive-npm-4.2.1-b86a9fb343-39cb49ed8c.zip"; sha512 = "39cb49ed8cf217fd6da058a92828a0a84e0b74c35550f82ee0a10e1ee403c4b78ade7948be2279b188b7a7303f5d396ea2738b134731e464bf28de00a4f72a18"; };
"aggregate-error@npm:3.1.0" = { filename = "aggregate-error-npm-3.1.0-415a406f4e-1101a33f21.zip"; sha512 = "1101a33f21baa27a2fa8e04b698271e64616b886795fd43c31068c07533c7b3facfcaf4e9e0cab3624bd88f729a592f1c901a1a229c9e490eafce411a8644b79"; };
"ansi-colors@npm:4.1.1" = { filename = "ansi-colors-npm-4.1.1-97ad42f223-138d04a510.zip"; sha512 = "138d04a51076cb085da0a7e2d000c5c0bb09f6e772ed5c65c53cb118d37f6c5f1637506d7155fb5f330f0abcf6f12fa2e489ac3f8cdab9da393bf1bb4f9a32b0"; };
"ansi-regex@npm:5.0.1" = { filename = "ansi-regex-npm-5.0.1-c963a48615-2aa4bb54ca.zip"; sha512 = "2aa4bb54caf2d622f1afdad09441695af2a83aa3fe8b8afa581d205e57ed4261c183c4d3877cee25794443fde5876417d859c108078ab788d6af7e4fe52eb66b"; };
"ansi-styles@npm:4.3.0" = { filename = "ansi-styles-npm-4.3.0-245c7d42c7-513b44c3b2.zip"; sha512 = "513b44c3b2105dd14cc42a19271e80f386466c4be574bccf60b627432f9198571ebf4ab1e4c3ba17347658f4ee1711c163d574248c0c1cdc2d5917a0ad582ec4"; };
"anymatch@npm:3.1.3" = { filename = "anymatch-npm-3.1.3-bc81d103b1-3e044fd6d1.zip"; sha512 = "3e044fd6d1d26545f235a9fe4d7a534e2029d8e59fa7fd9f2a6eb21230f6b5380ea1eaf55136e60cbf8e613544b3b766e7a6fa2102e2a3a117505466e3025dc2"; };
"aproba@npm:2.0.0" = { filename = "aproba-npm-2.0.0-8716bcfde6-5615cadcfb.zip"; sha512 = "5615cadcfb45289eea63f8afd064ab656006361020e1735112e346593856f87435e02d8dcc7ff0d11928bc7d425f27bc7c2a84f6c0b35ab0ff659c814c138a24"; };
"are-we-there-yet@npm:2.0.0" = { filename = "are-we-there-yet-npm-2.0.0-7d2f5201ce-6c80b4fd04.zip"; sha512 = "6c80b4fd04ecee6ba6e737e0b72a4b41bdc64b7d279edfc998678567ff583c8df27e27523bc789f2c99be603ffa9eaa612803da1d886962d2086e7ff6fa90c7c"; };
"are-we-there-yet@npm:3.0.1" = { filename = "are-we-there-yet-npm-3.0.1-3395b1512f-52590c2486.zip"; sha512 = "52590c24860fa7173bedeb69a4c05fb573473e860197f618b9a28432ee4379049336727ae3a1f9c4cb083114601c1140cee578376164d0e651217a9843f9fe83"; };
"argparse@npm:2.0.1" = { filename = "argparse-npm-2.0.1-faff7999e6-83644b5649.zip"; sha512 = "83644b56493e89a254bae05702abf3a1101b4fa4d0ca31df1c9985275a5a5bd47b3c27b7fa0b71098d41114d8ca000e6ed90cad764b306f8a503665e4d517ced"; };
"assertion-error@npm:1.1.0" = { filename = "assertion-error-npm-1.1.0-66b893015e-fd9429d3a3.zip"; sha512 = "fd9429d3a3d4fd61782eb3962ae76b6d08aa7383123fca0596020013b3ebd6647891a85b05ce821c47d1471ed1271f00b0545cf6a4326cf2fc91efcc3b0fbecf"; };
"async@npm:3.2.4" = { filename = "async-npm-3.2.4-aba13508f9-43d07459a4.zip"; sha512 = "43d07459a4e1d09b84a20772414aa684ff4de085cbcaec6eea3c7a8f8150e8c62aa6cd4e699fe8ee93c3a5b324e777d34642531875a0817a35697522c1b02e89"; };
"balanced-match@npm:1.0.2" = { filename = "balanced-match-npm-1.0.2-a53c126459-9706c088a2.zip"; sha512 = "9706c088a283058a8a99e0bf91b0a2f75497f185980d9ffa8b304de1d9e58ebda7c72c07ebf01dadedaac5b2907b2c6f566f660d62bd336c3468e960403b9d65"; };
"binary-extensions@npm:2.2.0" = { filename = "binary-extensions-npm-2.2.0-180c33fec7-ccd267956c.zip"; sha512 = "ccd267956c58d2315f5d3ea6757cf09863c5fc703e50fbeb13a7dc849b812ef76e3cf9ca8f35a0c48498776a7478d7b4a0418e1e2b8cb9cb9731f2922aaad7f8"; };
"brace-expansion@npm:1.1.11" = { filename = "brace-expansion-npm-1.1.11-fb95eb05ad-faf34a7bb0.zip"; sha512 = "faf34a7bb0c3fcf4b59c7808bc5d2a96a40988addf2e7e09dfbb67a2251800e0d14cd2bfc1aa79174f2f5095c54ff27f46fb1289fe2d77dac755b5eb3434cc07"; };
"brace-expansion@npm:2.0.1" = { filename = "brace-expansion-npm-2.0.1-17aa2616f9-a61e7cd2e8.zip"; sha512 = "a61e7cd2e8a8505e9f0036b3b6108ba5e926b4b55089eeb5550cd04a471fe216c96d4fe7e4c7f995c728c554ae20ddfc4244cad10aef255e72b62930afd233d1"; };
"braces@npm:3.0.2" = { filename = "braces-npm-3.0.2-782240b28a-e2a8e769a8.zip"; sha512 = "e2a8e769a863f3d4ee887b5fe21f63193a891c68b612ddb4b68d82d1b5f3ff9073af066c343e9867a393fe4c2555dcb33e89b937195feb9c1613d259edfcd459"; };
"browser-stdout@npm:1.3.1" = { filename = "browser-stdout-npm-1.3.1-6b2376bf3f-b717b19b25.zip"; sha512 = "b717b19b25952dd6af483e368f9bcd6b14b87740c3d226c2977a65e84666ffd67000bddea7d911f111a9b6ddc822b234de42d52ab6507bce4119a4cc003ef7b3"; };
"buffer-writer@npm:2.0.0" = { filename = "buffer-writer-npm-2.0.0-5cd2ef55bc-11736b48bb.zip"; sha512 = "11736b48bb75106c52ca8ec9f025e7c1b3b25ce31875f469d7210eabd5c576c329e34f6b805d4a8d605ff3f0db1e16342328802c4c963e9c826b0e43a4e631c2"; };
"busboy@npm:1.6.0" = { filename = "busboy-npm-1.6.0-ebb5cbb04b-32801e2c01.zip"; sha512 = "32801e2c0164e12106bf236291a00795c3c4e4b709ae02132883fe8478ba2ae23743b11c5735a0aae8afe65ac4b6ca4568b91f0d9fed1fdbc32ede824a73746e"; };
"bytes@npm:3.1.2" = { filename = "bytes-npm-3.1.2-28b8643004-e4bcd3948d.zip"; sha512 = "e4bcd3948d289c5127591fbedf10c0b639ccbf00243504e4e127374a15c3bc8eed0d28d4aaab08ff6f1cf2abc0cce6ba3085ed32f4f90e82a5683ce0014e1b6e"; };
"cacache@npm:16.1.3" = { filename = "cacache-npm-16.1.3-4e2088ed0d-d91409e6e5.zip"; sha512 = "d91409e6e57d7d9a3a25e5dcc589c84e75b178ae8ea7de05cbf6b783f77a5fae938f6e8fda6f5257ed70000be27a681e1e44829251bfffe4c10216002f8f14e6"; };
"cache-content-type@npm:1.0.1" = { filename = "cache-content-type-npm-1.0.1-f709f8c309-18db4d5945.zip"; sha512 = "18db4d59452669ccbfd7146a1510a37eb28e9eccf18ca7a4eb603dff2edc5cccdca7498fc3042a2978f76f11151fba486eb9eb69d9afa3fb124957870aef4fd3"; };
"cacheable-lookup@npm:7.0.0" = { filename = "cacheable-lookup-npm-7.0.0-b6cd95c14a-9e2856763f.zip"; sha512 = "9e2856763fc0a7347ab34d704c010440b819d4bb5e3593b664381b7433e942dd22e67ee5581f12256f908e79b82d30b86ebbacf40a081bfe10ee93fbfbc2d6a9"; };
"cacheable-request@npm:10.2.7" = { filename = "cacheable-request-npm-10.2.7-55f7290b84-25cfbe0cab.zip"; sha512 = "25cfbe0cab755bcee3bf6610b0253414e583289f795a28035616bf3186ecb303e8caf1943cbf42d92410b3f24124a1cdd663dd8ff52ac2c997a5129de5e9557a"; };
"call-bind@npm:1.0.2" = { filename = "call-bind-npm-1.0.2-c957124861-f8e31de9d1.zip"; sha512 = "f8e31de9d19988a4b80f3e704788c4a2d6b6f3d17cfec4f57dc29ced450c53a49270dc66bf0fbd693329ee948dd33e6c90a329519aef17474a4d961e8d6426b0"; };
"camelcase@npm:6.3.0" = { filename = "camelcase-npm-6.3.0-e5e42a0d15-8c96818a90.zip"; sha512 = "8c96818a9076434998511251dcb2761a94817ea17dbdc37f47ac080bd088fc62c7369429a19e2178b993497132c8cbcf5cc1f44ba963e76782ba469c0474938d"; };
"canonicalize@npm:1.0.8" = { filename = "canonicalize-npm-1.0.8-e87a0e7ee4-c31ea64160.zip"; sha512 = "c31ea64160171bbcd7ac0dc081058fbcff055410a1d532d7b3959e7b02a3001c5d5f4f8bad934ed5246eafc9a928d333cc0c29846c16fb6d0be97b8fb444de3c"; };
"canvas@npm:2.11.0" = { filename = "canvas-npm-2.11.0-1643476467-a69a6e0c90.zip"; sha512 = "a69a6e0c90014a1b02e52c4c38a627d1a01ffe9539047bec84105cb3554907a947cf39b4a333be43fc1583dd142b641bb5480a4e23f59c6098618c33bf78f67f"; };
"chai@npm:4.3.7" = { filename = "chai-npm-4.3.7-48fdcf2584-0bba7d2678.zip"; sha512 = "0bba7d267848015246a66995f044ce3f0ebc35e530da3cbdf171db744e14cbe301ab913a8d07caf7952b430257ccbb1a4a983c570a7c5748dc537897e5131f7c"; };
"chalk@npm:4.1.2" = { filename = "chalk-npm-4.1.2-ba8b67ab80-fe75c9d5c7.zip"; sha512 = "fe75c9d5c76a7a98d45495b91b2172fa3b7a09e0cc9370e5c8feb1c567b85c4288e2b3fded7cfdd7359ac28d6b3844feb8b82b8686842e93d23c827c417e83fc"; };
"check-error@npm:1.0.2" = { filename = "check-error-npm-1.0.2-00c540c6e9-d9d1065044.zip"; sha512 = "d9d106504404b8addd1ee3f63f8c0eaa7cd962a1a28eb9c519b1c4a1dc7098be38007fc0060f045ee00f075fbb7a2a4f42abcf61d68323677e11ab98dc16042e"; };
"chokidar@npm:3.5.3" = { filename = "chokidar-npm-3.5.3-c5f9b0a56a-b49fcde401.zip"; sha512 = "b49fcde40176ba007ff361b198a2d35df60d9bb2a5aab228279eb810feae9294a6b4649ab15981304447afe1e6ffbf4788ad5db77235dc770ab777c6e771980c"; };
"chownr@npm:2.0.0" = { filename = "chownr-npm-2.0.0-638f1c9c61-c57cf9dd07.zip"; sha512 = "c57cf9dd0791e2f18a5ee9c1a299ae6e801ff58fee96dc8bfd0dcb4738a6ce58dd252a3605b1c93c6418fe4f9d5093b28ffbf4d66648cb2a9c67eaef9679be2f"; };
"clean-stack@npm:2.2.0" = { filename = "clean-stack-npm-2.2.0-a8ce435a5c-2ac8cd2b2f.zip"; sha512 = "2ac8cd2b2f5ec986a3c743935ec85b07bc174d5421a5efc8017e1f146a1cf5f781ae962618f416352103b32c9cd7e203276e8c28241bbe946160cab16149fb68"; };
"cliui@npm:7.0.4" = { filename = "cliui-npm-7.0.4-d6b8a9edb6-ce2e8f578a.zip"; sha512 = "ce2e8f578a4813806788ac399b9e866297740eecd4ad1823c27fd344d78b22c5f8597d548adbcc46f0573e43e21e751f39446c5a5e804a12aace402b7a315d7f"; };
"co-body@npm:6.1.0" = { filename = "co-body-npm-6.1.0-8102b96671-d0a78831a6.zip"; sha512 = "d0a78831a6651f2085fce16b0ecdc49f45fb5baf4f94148c2f499e7ec89d188205362548b9c500eae15a819360cfda208079e68a72c204cf66ca3ffa2fc0f57e"; };
"co@npm:4.6.0" = { filename = "co-npm-4.6.0-03f2d1feb6-5210d92230.zip"; sha512 = "5210d9223010eb95b29df06a91116f2cf7c8e0748a9013ed853b53f362ea0e822f1e5bb054fb3cefc645239a4cf966af1f6133a3b43f40d591f3b68ed6cf0510"; };
"color-convert@npm:2.0.1" = { filename = "color-convert-npm-2.0.1-79730e935b-79e6bdb9fd.zip"; sha512 = "79e6bdb9fd479a205c71d89574fccfb22bd9053bd98c6c4d870d65c132e5e904e6034978e55b43d69fcaa7433af2016ee203ce76eeba9cfa554b373e7f7db336"; };
"color-name@npm:1.1.4" = { filename = "color-name-npm-1.1.4-025792b0ea-b044585952.zip"; sha512 = "b0445859521eb4021cd0fb0cc1a75cecf67fceecae89b63f62b201cca8d345baf8b952c966862a9d9a2632987d4f6581f0ec8d957dfacece86f0a7919316f610"; };
"color-support@npm:1.1.3" = { filename = "color-support-npm-1.1.3-3be5c53455-9b73568176.zip"; sha512 = "9b7356817670b9a13a26ca5af1c21615463b500783b739b7634a0c2047c16cef4b2865d7576875c31c3cddf9dd621fa19285e628f20198b233a5cfdda6d0793b"; };
"concat-map@npm:0.0.1" = { filename = "concat-map-npm-0.0.1-85a921b7ee-902a9f5d89.zip"; sha512 = "902a9f5d8967a3e2faf138d5cb784b9979bad2e6db5357c5b21c568df4ebe62bcb15108af1b2253744844eb964fc023fbd9afbbbb6ddd0bcc204c6fb5b7bf3af"; };
"console-control-strings@npm:1.1.0" = { filename = "console-control-strings-npm-1.1.0-e3160e5275-8755d76787.zip"; sha512 = "8755d76787f94e6cf79ce4666f0c5519906d7f5b02d4b884cf41e11dcd759ed69c57da0670afd9236d229a46e0f9cf519db0cd829c6dca820bb5a5c3def584ed"; };
"content-disposition@npm:0.5.4" = { filename = "content-disposition-npm-0.5.4-2d93678616-afb9d545e2.zip"; sha512 = "afb9d545e296a5171d7574fcad634b2fdf698875f4006a9dd04a3e1333880c5c0c98d47b560d01216fb6505a54a2ba6a843ee3a02ec86d7e911e8315255f56c3"; };
"content-type@npm:1.0.5" = { filename = "content-type-npm-1.0.5-3e037bf9ab-566271e0a2.zip"; sha512 = "566271e0a251642254cde0f845f9dd4f9856e52d988f4eb0d0dcffbb7a1f8ec98de7a5215fc628f3bce30fe2fb6fd2bc064b562d721658c59b544e2d34ea2766"; };
"cookies@npm:0.8.0" = { filename = "cookies-npm-0.8.0-d7388cbd94-806055a44f.zip"; sha512 = "806055a44f128705265b1bc6a853058da18bf80dea3654ad99be20985b1fa1b14f86c1eef73644aab8071241f8a78acd57202b54c4c5c70769fc694fbb9c4edc"; };
"data-uri-to-buffer@npm:4.0.1" = { filename = "data-uri-to-buffer-npm-4.0.1-5c66a78beb-0d0790b67f.zip"; sha512 = "0d0790b67ffec5302f204c2ccca4494f70b4e2d940fea3d36b09f0bb2b8539c2e86690429eb1f1dc4bcc9e4df0644193073e63d9ee48ac9fce79ec1506e4aa4c"; };
"debug@npm:4.3.4" = { filename = "debug-npm-4.3.4-4513954577-3dbad3f94e.zip"; sha512 = "3dbad3f94ea64f34431a9cbf0bafb61853eda57bff2880036153438f50fb5a84f27683ba0d8e5426bf41a8c6ff03879488120cf5b3a761e77953169c0600a708"; };
"decamelize@npm:4.0.0" = { filename = "decamelize-npm-4.0.0-12410e3409-b7d09b8265.zip"; sha512 = "b7d09b82652c39eead4d6678bb578e3bebd848add894b76d0f6b395bc45b2d692fb88d977e7cfb93c4ed6c119b05a1347cef261174916c2e75c0a8ca57da1809"; };
"decompress-response@npm:4.2.1" = { filename = "decompress-response-npm-4.2.1-abe5b4ebe4-4e783ca4df.zip"; sha512 = "4e783ca4dfe9417354d61349750fe05236f565a4415a6ca20983a311be2371debaedd9104c0b0e7b36e5f167aeaae04f84f1a0b3f8be4162f1d7d15598b8fdba"; };
"decompress-response@npm:6.0.0" = { filename = "decompress-response-npm-6.0.0-359de2878c-d377cf47e0.zip"; sha512 = "d377cf47e02d805e283866c3f50d3d21578b779731e8c5072d6ce8c13cc31493db1c2f6784da9d1d5250822120cefa44f1deab112d5981015f2e17444b763812"; };
"deep-eql@npm:4.1.3" = { filename = "deep-eql-npm-4.1.3-020a64f862-7f6d30cb41.zip"; sha512 = "7f6d30cb41c713973dc07eaadded848b2ab0b835e518a88b91bea72f34e08c4c71d167a722a6f302d3a6108f05afd8e6d7650689a84d5d29ec7fe6220420397f"; };
"deep-equal@npm:1.0.1" = { filename = "deep-equal-npm-1.0.1-f05565c4e5-5af8cbfceb.zip"; sha512 = "5af8cbfcebf190491878a498caccc7dc9592f8ebd1685b976eacc3825619d222b5e929923163b92c4f414494e2b884f7ebf00c022e8198e8292deb70dd9785f4"; };
"defer-to-connect@npm:2.0.1" = { filename = "defer-to-connect-npm-2.0.1-9005cc8c60-8a9b50d2f2.zip"; sha512 = "8a9b50d2f25446c0bfefb55a48e90afd58f85b21bcf78e9207cd7b804354f6409032a1705c2491686e202e64fc05f147aa5aa45f9aa82627563f045937f5791b"; };
"delegates@npm:1.0.0" = { filename = "delegates-npm-1.0.0-9b1942d75f-a51744d9b5.zip"; sha512 = "a51744d9b53c164ba9c0492471a1a2ffa0b6727451bdc89e31627fdf4adda9d51277cfcbfb20f0a6f08ccb3c436f341df3e92631a3440226d93a8971724771fd"; };
"depd@npm:1.1.2" = { filename = "depd-npm-1.1.2-b0c8414da7-6b406620d2.zip"; sha512 = "6b406620d269619852885ce15965272b829df6f409724415e0002c8632ab6a8c0a08ec1f0bd2add05dc7bd7507606f7e2cc034fa24224ab829580040b835ecd9"; };
"depd@npm:2.0.0" = { filename = "depd-npm-2.0.0-b6c51a4b43-abbe19c768.zip"; sha512 = "abbe19c768c97ee2eed6282d8ce3031126662252c58d711f646921c9623f9052e3e1906443066beec1095832f534e57c523b7333f8e7e0d93051ab6baef5ab3a"; };
"destroy@npm:1.2.0" = { filename = "destroy-npm-1.2.0-6a511802e2-0acb300b74.zip"; sha512 = "0acb300b7478a08b92d810ab229d5afe0d2f4399272045ab22affa0d99dbaf12637659411530a6fcd597a9bdac718fc94373a61a95b4651bbc7b83684a565e38"; };
"detect-libc@npm:2.0.1" = { filename = "detect-libc-npm-2.0.1-2699cb2ac4-ccb05fcabb.zip"; sha512 = "ccb05fcabbb555beb544d48080179c18523a343face9ee4e1a86605a8715b4169f94d663c21a03c310ac824592f2ba9a5270218819bb411ad7be578a527593d7"; };
"diff@npm:5.0.0" = { filename = "diff-npm-5.0.0-ad6900db18-f19fe29284.zip"; sha512 = "f19fe29284b633afdb2725c2a8bb7d25761ea54d321d8e67987ac851c5294be4afeab532bd84531e02583a3fe7f4014aa314a3eda84f5590e7a9e6b371ef3b46"; };
"dotenv@npm:16.0.3" = { filename = "dotenv-npm-16.0.3-4cc29121dc-afcf03f373.zip"; sha512 = "afcf03f373d7a6d62c7e9afea6328e62851d627a4e73f2e12d0a8deae1cd375892004f3021883f8aec85932cd2834b091f568ced92b4774625b321db83b827f8"; };
"ee-first@npm:1.1.1" = { filename = "ee-first-npm-1.1.1-33f8535b39-1b4cac778d.zip"; sha512 = "1b4cac778d64ce3b582a7e26b218afe07e207a0f9bfe13cc7395a6d307849cfe361e65033c3251e00c27dd060cab43014c2d6b2647676135e18b77d2d05b3f4f"; };
"ejs@npm:3.1.8" = { filename = "ejs-npm-3.1.8-30583753fc-1d40d198ad.zip"; sha512 = "1d40d198ad52e315ccf37e577bdec06e24eefdc4e3c27aafa47751a03a0c7f0ec4310254c9277a5f14763c3cd4bbacce27497332b2d87c74232b9b1defef8efc"; };
"emoji-regex@npm:8.0.0" = { filename = "emoji-regex-npm-8.0.0-213764015c-d4c5c39d5a.zip"; sha512 = "d4c5c39d5a9868b5fa152f00cada8a936868fd3367f33f71be515ecee4c803132d11b31a6222b2571b1e5f7e13890156a94880345594d0ce7e3c9895f560f192"; };
"encodeurl@npm:1.0.2" = { filename = "encodeurl-npm-1.0.2-f8c8454c41-e50e3d508c.zip"; sha512 = "e50e3d508cdd9c4565ba72d2012e65038e5d71bdc9198cb125beb6237b5b1ade6c0d343998da9e170fb2eae52c1bed37d4d6d98a46ea423a0cddbed5ac3f780c"; };
"encoding@npm:0.1.13" = { filename = "encoding-npm-0.1.13-82a1837d30-bb98632f8f.zip"; sha512 = "bb98632f8ffa823996e508ce6a58ffcf5856330fde839ae42c9e1f436cc3b5cc651d4aeae72222916545428e54fd0f6aa8862fd8d25bdbcc4589f1e3f3715e7f"; };
"entities@npm:4.4.0" = { filename = "entities-npm-4.4.0-97635dc5cc-84d250329f.zip"; sha512 = "84d250329f4b56b40fa93ed067b194db21e8815e4eb9b59f43a086f0ecd342814f6bc483de8a77da5d64e0f626033192b1b4f1792232a7ea6b970ebe0f3187c2"; };
"env-paths@npm:2.2.1" = { filename = "env-paths-npm-2.2.1-7c7577428c-65b5df55a8.zip"; sha512 = "65b5df55a8bab92229ab2b40dad3b387fad24613263d103a97f91c9fe43ceb21965cd3392b1ccb5d77088021e525c4e0481adb309625d0cb94ade1d1fb8dc17e"; };
"err-code@npm:2.0.3" = { filename = "err-code-npm-2.0.3-082e0ff9a7-8b7b1be20d.zip"; sha512 = "8b7b1be20d2de12d2255c0bc2ca638b7af5171142693299416e6a9339bd7d88fc8d7707d913d78e0993176005405a236b066b45666b27b797252c771156ace54"; };
"escalade@npm:3.1.1" = { filename = "escalade-npm-3.1.1-e02da076aa-a3e2a99f07.zip"; sha512 = "a3e2a99f07acb74b3ad4989c48ca0c3140f69f923e56d0cba0526240ee470b91010f9d39001f2a4a313841d237ede70a729e92125191ba5d21e74b106800b133"; };
"escape-html@npm:1.0.3" = { filename = "escape-html-npm-1.0.3-376c22ee74-6213ca9ae0.zip"; sha512 = "6213ca9ae00d0ab8bccb6d8d4e0a98e76237b2410302cf7df70aaa6591d509a2a37ce8998008cbecae8fc8ffaadf3fb0229535e6a145f3ce0b211d060decbb24"; };
"escape-string-regexp@npm:4.0.0" = { filename = "escape-string-regexp-npm-4.0.0-4b531d8d59-98b48897d9.zip"; sha512 = "98b48897d93060f2322108bf29db0feba7dd774be96cd069458d1453347b25ce8682ecc39859d4bca2203cc0ab19c237bcc71755eff49a0f8d90beadeeba5cc5"; };
"event-target-shim@npm:5.0.1" = { filename = "event-target-shim-npm-5.0.1-cb48709025-1ffe3bb22a.zip"; sha512 = "1ffe3bb22a6d51bdeb6bf6f7cf97d2ff4a74b017ad12284cc9e6a279e727dc30a5de6bb613e5596ff4dc3e517841339ad09a7eec44266eccb1aa201a30448166"; };
"fetch-blob@npm:3.2.0" = { filename = "fetch-blob-npm-3.2.0-28e01becfc-f19bc28a2a.zip"; sha512 = "f19bc28a2a0b9626e69fd7cf3a05798706db7f6c7548da657cbf5026a570945f5eeaedff52007ea35c8bcd3d237c58a20bf1543bc568ab2422411d762dd3d5bf"; };
"filelist@npm:1.0.4" = { filename = "filelist-npm-1.0.4-3a835ae0a7-a303573b08.zip"; sha512 = "a303573b0821e17f2d5e9783688ab6fbfce5d52aaac842790ae85e704a6f5e4e3538660a63183d6453834dedf1e0f19a9dadcebfa3e926c72397694ea11f5160"; };
"fill-range@npm:7.0.1" = { filename = "fill-range-npm-7.0.1-b8b1817caa-cc283f4e65.zip"; sha512 = "cc283f4e65b504259e64fd969bcf4def4eb08d85565e906b7d36516e87819db52029a76b6363d0f02d0d532f0033c9603b9e2d943d56ee3b0d4f7ad3328ff917"; };
"find-up@npm:5.0.0" = { filename = "find-up-npm-5.0.0-e03e9b796d-07955e3573.zip"; sha512 = "07955e357348f34660bde7920783204ff5a26ac2cafcaa28bace494027158a97b9f56faaf2d89a6106211a8174db650dd9f503f9c0d526b1202d5554a00b9095"; };
"flat@npm:5.0.2" = { filename = "flat-npm-5.0.2-12748102a5-12a1536ac7.zip"; sha512 = "12a1536ac746db74881316a181499a78ef953632ddd28050b7a3a43c62ef5462e3357c8c29d76072bb635f147f7a9a1f0c02efef6b4be28f8db62ceb3d5c7f5d"; };
"form-data-encoder@npm:2.1.4" = { filename = "form-data-encoder-npm-2.1.4-6f48cca6c9-e0b3e5950f.zip"; sha512 = "e0b3e5950fb69b3f32c273944620f9861f1933df9d3e42066e038e26dfb343d0f4465de9f27e0ead1a09d9df20bc2eed06a63c2ca2f8f00949e7202bae9e29dd"; };
"formdata-polyfill@npm:4.0.10" = { filename = "formdata-polyfill-npm-4.0.10-e03013c013-82a34df292.zip"; sha512 = "82a34df292afadd82b43d4a740ce387bc08541e0a534358425193017bf9fb3567875dc5f69564984b1da979979b70703aa73dee715a17b6c229752ae736dd9db"; };
"fresh@npm:0.5.2" = { filename = "fresh-npm-0.5.2-ad2bb4c0a2-13ea8b08f9.zip"; sha512 = "13ea8b08f91e669a64e3ba3a20eb79d7ca5379a81f1ff7f4310d54e2320645503cc0c78daedc93dfb6191287295f6479544a649c64d8e41a1c0fb0c221552346"; };
"fs-minipass@npm:2.1.0" = { filename = "fs-minipass-npm-2.1.0-501ef87306-1b8d128dae.zip"; sha512 = "1b8d128dae2ac6cc94230cc5ead341ba3e0efaef82dab46a33d171c044caaa6ca001364178d42069b2809c35a1c3c35079a32107c770e9ffab3901b59af8c8b1"; };
"fs.realpath@npm:1.0.0" = { filename = "fs.realpath-npm-1.0.0-c8f05d8126-99ddea01a7.zip"; sha512 = "99ddea01a7e75aa276c250a04eedeffe5662bce66c65c07164ad6264f9de18fb21be9433ead460e54cff20e31721c811f4fb5d70591799df5f85dce6d6746fd0"; };
"fsevents@npm:2.3.2" = { filename = "fsevents-npm-2.3.2-a881d6ac9f-97ade64e75.zip"; sha512 = "97ade64e75091afee5265e6956cb72ba34db7819b4c3e94c431d4be2b19b8bb7a2d4116da417950c3425f17c8fe693d25e20212cac583ac1521ad066b77ae31f"; };
"fsevents@patch:fsevents@npm%3A2.3.2#~builtin<compat/fsevents>::version=2.3.2&hash=df0bf1" = { filename = "fsevents-patch-2882183fbf-8.zip"; sha512 = "edbd0fd80be379c14409605f77e52fdc78a119e17f875e8b90a220c3e5b29e54a1477c21d91fd30b957ea4866406dc3ff87b61432d2840ff8866b309e5866140"; };
"function-bind@npm:1.1.1" = { filename = "function-bind-npm-1.1.1-b56b322ae9-b32fbaebb3.zip"; sha512 = "b32fbaebb3f8ec4969f033073b43f5c8befbb58f1a79e12f1d7490358150359ebd92f49e72ff0144f65f2c48ea2a605bff2d07965f548f6474fd8efd95bf361a"; };
"gauge@npm:3.0.2" = { filename = "gauge-npm-3.0.2-9e22f7af9e-81296c00c7.zip"; sha512 = "81296c00c7410cdd48f997800155fbead4f32e4f82109be0719c63edc8560e6579946cc8abd04205297640691ec26d21b578837fd13a4e96288ab4b40b1dc3e9"; };
"gauge@npm:4.0.4" = { filename = "gauge-npm-4.0.4-8f878385e9-788b6bfe52.zip"; sha512 = "788b6bfe52f1dd8e263cda800c26ac0ca2ff6de0b6eee2fe0d9e3abf15e149b651bd27bf5226be10e6e3edb5c4e5d5985a5a1a98137e7a892f75eff76467ad2d"; };
"get-caller-file@npm:2.0.5" = { filename = "get-caller-file-npm-2.0.5-80e8a86305-b9769a836d.zip"; sha512 = "b9769a836d2a98c3ee734a88ba712e62703f1df31b94b784762c433c27a386dd6029ff55c2a920c392e33657d80191edbf18c61487e198844844516f843496b9"; };
"get-func-name@npm:2.0.0" = { filename = "get-func-name-npm-2.0.0-afbf363765-8d82e69f3e.zip"; sha512 = "8d82e69f3e7fab9e27c547945dfe5cc0c57fc0adf08ce135dddb01081d75684a03e7a0487466f478872b341d52ac763ae49e660d01ab83741f74932085f693c3"; };
"get-intrinsic@npm:1.2.0" = { filename = "get-intrinsic-npm-1.2.0-eb08ea9b1d-78fc0487b7.zip"; sha512 = "78fc0487b783f5c58cf2dccafc3ae656ee8d2d8062a8831ce4a95e7057af4587a1d4882246c033aca0a7b4965276f4802b45cc300338d1b77a73d3e3e3f4877d"; };
"get-stream@npm:6.0.1" = { filename = "get-stream-npm-6.0.1-83e51a4642-e04ecece32.zip"; sha512 = "e04ecece32c92eebf5b8c940f51468cd53554dcbb0ea725b2748be583c9523d00128137966afce410b9b051eb2ef16d657cd2b120ca8edafcf5a65e81af63cad"; };
"glob-parent@npm:5.1.2" = { filename = "glob-parent-npm-5.1.2-021ab32634-f4f2bfe242.zip"; sha512 = "f4f2bfe2425296e8a47e36864e4f42be38a996db40420fe434565e4480e3322f18eb37589617a98640c5dc8fdec1a387007ee18dbb1f3f5553409c34d17f425e"; };
"glob@npm:7.2.0" = { filename = "glob-npm-7.2.0-bb4644d239-78a8ea9423.zip"; sha512 = "78a8ea942331f08ed2e055cb5b9e40fe6f46f579d7fd3d694f3412fe5db23223d29b7fee1575440202e9a7ff9a72ab106a39fee39934c7bedafe5e5f8ae20134"; };
"glob@npm:7.2.3" = { filename = "glob-npm-7.2.3-2d866d17a5-29452e97b3.zip"; sha512 = "29452e97b38fa704dabb1d1045350fb2467cf0277e155aa9ff7077e90ad81d1ea9d53d3ee63bd37c05b09a065e90f16aec4a65f5b8de401d1dac40bc5605d133"; };
"glob@npm:8.1.0" = { filename = "glob-npm-8.1.0-65f64af8b1-92fbea3221.zip"; sha512 = "92fbea3221a7d12075f26f0227abac435de868dd0736a17170663783296d0dd8d3d532a5672b4488a439bf5d7fb85cdd07c11185d6cd39184f0385cbdfb86a47"; };
"got@npm:12.5.3" = { filename = "got-npm-12.5.3-7876a3e67a-e35ea3ccdb.zip"; sha512 = "e35ea3ccdb5f2c36d0bb9648a6a87300d017900ce2e647ad95f54a6fb674a82fe7d53b2c838542d15a9fa25290cc5361d6f82cadac3e94b2e91d93b5670cf304"; };
"graceful-fs@npm:4.2.10" = { filename = "graceful-fs-npm-4.2.10-79c70989ca-3f109d70ae.zip"; sha512 = "3f109d70ae123951905d85032ebeae3c2a5a7a997430df00ea30df0e3a6c60cf6689b109654d6fdacd28810a053348c4d14642da1d075049e6be1ba5216218da"; };
"has-flag@npm:4.0.0" = { filename = "has-flag-npm-4.0.0-32af9f0536-261a135703.zip"; sha512 = "261a1357037ead75e338156b1f9452c016a37dcd3283a972a30d9e4a87441ba372c8b81f818cd0fbcd9c0354b4ae7e18b9e1afa1971164aef6d18c2b6095a8ad"; };
"has-symbols@npm:1.0.3" = { filename = "has-symbols-npm-1.0.3-1986bff2c4-a054c40c63.zip"; sha512 = "a054c40c631c0d5741a8285010a0777ea0c068f99ed43e5d6eb12972da223f8af553a455132fdb0801bdcfa0e0f443c0c03a68d8555aa529b3144b446c3f2410"; };
"has-tostringtag@npm:1.0.0" = { filename = "has-tostringtag-npm-1.0.0-b1fcf3ab55-cc12eb28cb.zip"; sha512 = "cc12eb28cb6ae22369ebaad3a8ab0799ed61270991be88f208d508076a1e99abe4198c965935ce85ea90b60c94ddda73693b0920b58e7ead048b4a391b502c1c"; };
"has-unicode@npm:2.0.1" = { filename = "has-unicode-npm-2.0.1-893adb4747-1eab07a743.zip"; sha512 = "1eab07a7436512db0be40a710b29b5dc21fa04880b7f63c9980b706683127e3c1b57cb80ea96d47991bdae2dfe479604f6a1ba410106ee1046a41d1bd0814400"; };
"has@npm:1.0.3" = { filename = "has-npm-1.0.3-b7f00631c1-b9ad53d53b.zip"; sha512 = "b9ad53d53be4af90ce5d1c38331e712522417d017d5ef1ebd0507e07c2fbad8686fffb8e12ddecd4c39ca9b9b47431afbb975b8abf7f3c3b82c98e9aad052792"; };
"he@npm:1.2.0" = { filename = "he-npm-1.2.0-3b73a2ff07-3d4d6babcc.zip"; sha512 = "3d4d6babccccd79c5c5a3f929a68af33360d6445587d628087f39a965079d84f18ce9c3d3f917ee1e3978916fc833bb8b29377c3b403f919426f91bc6965e7a7"; };
"http-assert@npm:1.5.0" = { filename = "http-assert-npm-1.5.0-bf7ea4ffcf-69c9b3c14c.zip"; sha512 = "69c9b3c14cf8b2822916360a365089ce936c883c49068f91c365eccba5c141a9964d19fdda589150a480013bf503bf37d8936c732e9635819339e730ab0e7527"; };
"http-cache-semantics@npm:4.1.1" = { filename = "http-cache-semantics-npm-4.1.1-1120131375-83ac0bc60b.zip"; sha512 = "83ac0bc60b17a3a36f9953e7be55e5c8f41acc61b22583060e8dedc9dd5e3607c823a88d0926f9150e571f90946835c7fe150732801010845c72cd8bbff1a236"; };
"http-errors@npm:1.8.1" = { filename = "http-errors-npm-1.8.1-fb60d9f6ae-d3c7e7e776.zip"; sha512 = "d3c7e7e776fd51c0a812baff570bdf06fe49a5dc448b700ab6171b1250e4cf7db8b8f4c0b133e4bfe2451022a5790c1ca6c2cae4094dedd6ac8304a1267f91d2"; };
"http-errors@npm:2.0.0" = { filename = "http-errors-npm-2.0.0-3f1c503428-9b0a378266.zip"; sha512 = "9b0a3782665c52ce9dc658a0d1560bcb0214ba5699e4ea15aefb2a496e2ca83db03ebc42e1cce4ac1f413e4e0d2d736a3fd755772c556a9a06853ba2a0b7d920"; };
"http-proxy-agent@npm:5.0.0" = { filename = "http-proxy-agent-npm-5.0.0-7f1f121b83-e2ee1ff165.zip"; sha512 = "e2ee1ff1656a131953839b2a19cd1f3a52d97c25ba87bd2559af6ae87114abf60971e498021f9b73f9fd78aea8876d1fb0d4656aac8a03c6caa9fc175f22b786"; };
"http2-wrapper@npm:2.2.0" = { filename = "http2-wrapper-npm-2.2.0-6fbf58bfd7-6fd20e5cb6.zip"; sha512 = "6fd20e5cb6a58151715b3581e06a62a47df943187d2d1f69e538a50cccb7175dd334ecfde7900a37d18f3e13a1a199518a2c211f39860e81e9a16210c199cfaa"; };
"https-proxy-agent@npm:5.0.1" = { filename = "https-proxy-agent-npm-5.0.1-42d65f358e-571fccdf38.zip"; sha512 = "571fccdf38184f05943e12d37d6ce38197becdd69e58d03f43637f7fa1269cf303a7d228aa27e5b27bbd3af8f09fd938e1c91dcfefff2df7ba77c20ed8dfc765"; };
"humanize-ms@npm:1.2.1" = { filename = "humanize-ms-npm-1.2.1-e942bd7329-9c7a74a282.zip"; sha512 = "9c7a74a2827f9294c009266c82031030eae811ca87b0da3dceb8d6071b9bde22c9f3daef0469c3c533cc67a97d8a167cd9fc0389350e5f415f61a79b171ded16"; };
"iconv-lite@npm:0.4.24" = { filename = "iconv-lite-npm-0.4.24-c5c4ac6695-bd9f120f5a.zip"; sha512 = "bd9f120f5a5b306f0bc0b9ae1edeb1577161503f5f8252a20f1a9e56ef8775c9959fd01c55f2d3a39d9a8abaf3e30c1abeb1895f367dcbbe0a8fd1c9ca01c4f6"; };
"iconv-lite@npm:0.6.3" = { filename = "iconv-lite-npm-0.6.3-24b8aae27e-3f60d47a5c.zip"; sha512 = "3f60d47a5c8fc3313317edfd29a00a692cc87a19cac0159e2ce711d0ebc9019064108323b5e493625e25594f11c6236647d8e256fbe7a58f4a3b33b89e6d30bf"; };
"imurmurhash@npm:0.1.4" = { filename = "imurmurhash-npm-0.1.4-610c5068a0-7cae75c8cd.zip"; sha512 = "7cae75c8cd9a50f57dadd77482359f659eaebac0319dd9368bcd1714f55e65badd6929ca58569da2b6494ef13fdd5598cd700b1eba23f8b79c5f19d195a3ecf7"; };
"indent-string@npm:4.0.0" = { filename = "indent-string-npm-4.0.0-7b717435b2-824cfb9929.zip"; sha512 = "824cfb9929d031dabf059bebfe08cf3137365e112019086ed3dcff6a0a7b698cb80cf67ccccde0e25b9e2d7527aa6cc1fed1ac490c752162496caba3e6699612"; };
"infer-owner@npm:1.0.4" = { filename = "infer-owner-npm-1.0.4-685ac3d2af-181e732764.zip"; sha512 = "181e732764e4a0611576466b4b87dac338972b839920b2a8cde43642e4ed6bd54dc1fb0b40874728f2a2df9a1b097b8ff83b56d5f8f8e3927f837fdcb47d8a89"; };
"inflation@npm:2.0.0" = { filename = "inflation-npm-2.0.0-e638c91672-a0494871b1.zip"; sha512 = "a0494871b12275afdef9e2710ee1af1e0fc642b04613a9be69c05ef8b5e9627f3bd7d358a937fa47aa20235ee7313a4f30255048533add0ad4918beb918a586e"; };
"inflight@npm:1.0.6" = { filename = "inflight-npm-1.0.6-ccedb4b908-f4f76aa072.zip"; sha512 = "f4f76aa072ce19fae87ce1ef7d221e709afb59d445e05d47fba710e85470923a75de35bfae47da6de1b18afc3ce83d70facf44cfb0aff89f0a3f45c0a0244dfd"; };
"inherits@npm:2.0.4" = { filename = "inherits-npm-2.0.4-c66b3957a0-4a48a73384.zip"; sha512 = "4a48a733847879d6cf6691860a6b1e3f0f4754176e4d71494c41f3475553768b10f84b5ce1d40fbd0e34e6bfbb864ee35858ad4dd2cf31e02fc4a154b724d7f1"; };
"ip@npm:2.0.0" = { filename = "ip-npm-2.0.0-204facb3cc-cfcfac6b87.zip"; sha512 = "cfcfac6b873b701996d71ec82a7dd27ba92450afdb421e356f44044ed688df04567344c36cbacea7d01b1c39a4c732dc012570ebe9bebfb06f27314bca625349"; };
"is-binary-path@npm:2.1.0" = { filename = "is-binary-path-npm-2.1.0-e61d46f557-84192eb88c.zip"; sha512 = "84192eb88cff70d320426f35ecd63c3d6d495da9d805b19bc65b518984b7c0760280e57dbf119b7e9be6b161784a5a673ab2c6abe83abb5198a432232ad5b35c"; };
"is-extglob@npm:2.1.1" = { filename = "is-extglob-npm-2.1.1-0870ea68b5-df033653d0.zip"; sha512 = "df033653d06d0eb567461e58a7a8c9f940bd8c22274b94bf7671ab36df5719791aae15eef6d83bbb5e23283967f2f984b8914559d4449efda578c775c4be6f85"; };
"is-fullwidth-code-point@npm:3.0.0" = { filename = "is-fullwidth-code-point-npm-3.0.0-1ecf4ebee5-44a30c2945.zip"; sha512 = "44a30c29457c7fb8f00297bce733f0a64cd22eca270f83e58c105e0d015e45c019491a4ab2faef91ab51d4738c670daff901c799f6a700e27f7314029e99e348"; };
"is-generator-function@npm:1.0.10" = { filename = "is-generator-function-npm-1.0.10-1d0f3809ef-d54644e7db.zip"; sha512 = "d54644e7dbaccef15ceb1e5d91d680eb5068c9ee9f9eb0a9e04173eb5542c9b51b5ab52c5537f5703e48d5fddfd376817c1ca07a84a407b7115b769d4bdde72b"; };
"is-glob@npm:4.0.3" = { filename = "is-glob-npm-4.0.3-cb87bf1bdb-d381c1319f.zip"; sha512 = "d381c1319fcb69d341cc6e6c7cd588e17cd94722d9a32dbd60660b993c4fb7d0f19438674e68dfec686d09b7c73139c9166b47597f846af387450224a8101ab4"; };
"is-lambda@npm:1.0.1" = { filename = "is-lambda-npm-1.0.1-7ab55bc8a8-93a32f0194.zip"; sha512 = "93a32f01940220532e5948538699ad610d5924ac86093fcee83022252b363eb0cc99ba53ab084a04e4fb62bf7b5731f55496257a4c38adf87af9c4d352c71c35"; };
"is-number@npm:7.0.0" = { filename = "is-number-npm-7.0.0-060086935c-456ac6f8e0.zip"; sha512 = "456ac6f8e0f3111ed34668a624e45315201dff921e5ac181f8ec24923b99e9f32ca1a194912dc79d539c97d33dba17dc635202ff0b2cf98326f608323276d27a"; };
"is-plain-obj@npm:2.1.0" = { filename = "is-plain-obj-npm-2.1.0-8dffd7ae9c-cec9100678.zip"; sha512 = "cec9100678b0a9fe0248a81743041ed990c2d4c99f893d935545cfbc42876cbe86d207f3b895700c690ad2fa520e568c44afc1605044b535a7820c1d40e38daa"; };
"is-unicode-supported@npm:0.1.0" = { filename = "is-unicode-supported-npm-0.1.0-0833e1bbfb-a2aab86ee7.zip"; sha512 = "a2aab86ee7712f5c2f999180daaba5f361bdad1efadc9610ff5b8ab5495b86e4f627839d085c6530363c6d6d4ecbde340fb8e54bdb83da4ba8e0865ed5513c52"; };
"isexe@npm:2.0.0" = { filename = "isexe-npm-2.0.0-b58870bd2e-26bf6c5480.zip"; sha512 = "26bf6c5480dda5161c820c5b5c751ae1e766c587b1f951ea3fcfc973bafb7831ae5b54a31a69bd670220e42e99ec154475025a468eae58ea262f813fdc8d1c62"; };
"jake@npm:10.8.5" = { filename = "jake-npm-10.8.5-6a5e87e533-56c913ecf5.zip"; sha512 = "56c913ecf5a8d74325d0af9bc17a233bad50977438d44864d925bb6c45c946e0fee8c4c1f5fe2225471ef40df5222e943047982717ebff0d624770564d3c46ba"; };
"js-yaml@npm:4.1.0" = { filename = "js-yaml-npm-4.1.0-3606f32312-c7830dfd45.zip"; sha512 = "c7830dfd456c3ef2c6e355cc5a92e6700ceafa1d14bba54497b34a99f0376cecbb3e9ac14d3e5849b426d5a5140709a66237a8c991c675431271c4ce5504151a"; };
"json-buffer@npm:3.0.1" = { filename = "json-buffer-npm-3.0.1-f8f6d20603-9026b03edc.zip"; sha512 = "9026b03edc2847eefa2e37646c579300a1f3a4586cfb62bf857832b60c852042d0d6ae55d1afb8926163fa54c2b01d83ae24705f34990348bdac6273a29d4581"; };
"jsonld@npm:8.1.0" = { filename = "jsonld-npm-8.1.0-b53d73de36-0ddea3941e.zip"; sha512 = "0ddea3941ec8c880e761eb26b4fff140961ac4cecd41cf81912bd9a159f9474b6ab116bfe860bb8a16a703341f0ef74e6043ec6e1b3ee3ad21a921b642891ff1"; };
"keygrip@npm:1.1.0" = { filename = "keygrip-npm-1.1.0-8da030c3ff-078cd16a46.zip"; sha512 = "078cd16a463d187121f0a27c1c9c95c52ad392b620f823431689f345a0501132cee60f6e96914b07d570105af470b96960402accd6c48a0b1f3cd8fac4fa2cae"; };
"keyv@npm:4.5.2" = { filename = "keyv-npm-4.5.2-78a8ba8062-13ad58303a.zip"; sha512 = "13ad58303acd2261c0d4831b4658451603fd159e61daea2121fcb15feb623e75ee328cded0572da9ca76b7b3ceaf8e614f1806c6b3af5db73c9c35a345259651"; };
"koa-compose@npm:4.1.0" = { filename = "koa-compose-npm-4.1.0-b682d9324e-46cb16792d.zip"; sha512 = "46cb16792d96425e977c2ae4e5cb04930280740e907242ec9c25e3fb8b4a1d7b54451d7432bc24f40ec62255edea71894d2ceeb8238501842b4e48014f2e83db"; };
"koa-convert@npm:2.0.0" = { filename = "koa-convert-npm-2.0.0-d709eca55c-7385b33919.zip"; sha512 = "7385b3391995f59c1312142e110d5dff677f9850dbfbcf387cd36a7b0af03b5d26e82b811eb9bb008b4f3e661cdab1f8817596e46b1929da2cf6e97a2f7456ed"; };
"koa@npm:2.14.1" = { filename = "koa-npm-2.14.1-92dad86c35-84cfce48d7.zip"; sha512 = "84cfce48d72cf434831bd9f4f06beb3815da030325a7e89b13ee684f5afd158221e16c2d450ca637b221aa0c4a0ab235edd129e4efea656dc5d8384801d3e90f"; };
"ky-universal@npm:0.11.0" = { filename = "ky-universal-npm-0.11.0-f343804243-42e4c91551.zip"; sha512 = "42e4c91551a0d17465d6a117de2d1fa4efdf38c4e29dbd70af0c5b7ac0ee13994bceca9af2a0ac21a943d1cd22557ea664abe79f25e096d30a6baca0a0265a12"; };
"ky@npm:0.33.2" = { filename = "ky-npm-0.33.2-962f722db7-bb5b1685b7.zip"; sha512 = "bb5b1685b7d639dad5fc0a41a218f76c2400d2a9189bcf747f541633af13b68a7ef12bb8aa971bc1667087789ec5965cc3728e24b693897a2d0cc539d7593655"; };
"leven@npm:4.0.0" = { filename = "leven-npm-4.0.0-7caa3158fb-d70b9fef4c.zip"; sha512 = "d70b9fef4cca487a38021bb173a5cae98d39b1c7f4a5b2439763bd89df8e389f178a3c941b6fc3fab1582f5052b5e8c91353d9607799a2ad3841e7ea22f9720f"; };
"locate-path@npm:6.0.0" = { filename = "locate-path-npm-6.0.0-06a1e4c528-72eb661788.zip"; sha512 = "72eb661788a0368c099a184c59d2fee760b3831c9c1c33955e8a19ae4a21b4116e53fa736dc086cdeb9fce9f7cc508f2f92d2d3aae516f133e16a2bb59a39f5a"; };
"log-symbols@npm:4.1.0" = { filename = "log-symbols-npm-4.1.0-0a13492d8b-fce1497b31.zip"; sha512 = "fce1497b3135a0198803f9f07464165e9eb83ed02ceb2273930a6f8a508951178d8cf4f0378e9d28300a2ed2bc49050995d2bd5f53ab716bb15ac84d58c6ef74"; };
"loupe@npm:2.3.6" = { filename = "loupe-npm-2.3.6-b8b37d55e7-cc83f1b124.zip"; sha512 = "cc83f1b124a1df7384601d72d8d1f5fe95fd7a8185469fec48bb2e4027e45243949e7a013e8d91051a138451ff0552310c32aa9786e60b6a30d1e801bdc2163f"; };
"lowercase-keys@npm:3.0.0" = { filename = "lowercase-keys-npm-3.0.0-f8c4730215-67a3f81409.zip"; sha512 = "67a3f81409af969bc0c4ca0e76cd7d16adb1e25aa1c197229587eaf8671275c8c067cd421795dbca4c81be0098e4c426a086a05e30de8a9c587b7a13c0c7ccc5"; };
"lru-cache@npm:6.0.0" = { filename = "lru-cache-npm-6.0.0-b4c8668fe1-f97f499f89.zip"; sha512 = "f97f499f898f23e4585742138a22f22526254fdba6d75d41a1c2526b3b6cc5747ef59c5612ba7375f42aca4f8461950e925ba08c991ead0651b4918b7c978297"; };
"lru-cache@npm:7.14.1" = { filename = "lru-cache-npm-7.14.1-d3ba9407b6-d72c6713c6.zip"; sha512 = "d72c6713c6a6d86836a7a6523b3f1ac6764768cca47ec99341c3e76db06aacd4764620e5e2cda719a36848785a52a70e531822dc2b33fb071fa709683746c104"; };
"make-dir@npm:3.1.0" = { filename = "make-dir-npm-3.1.0-d1d7505142-484200020a.zip"; sha512 = "484200020ab5a1fdf12f393fe5f385fc8e4378824c940fba1729dcd198ae4ff24867bc7a5646331e50cead8abff5d9270c456314386e629acec6dff4b8016b78"; };
"make-fetch-happen@npm:10.2.1" = { filename = "make-fetch-happen-npm-10.2.1-f1cc7cd2df-2332eb9a8e.zip"; sha512 = "2332eb9a8ec96f1ffeeea56ccefabcb4193693597b132cd110734d50f2928842e22b84cfa1508e921b8385cdfd06dda9ad68645fed62b50fff629a580f5fb72c"; };
"media-typer@npm:0.3.0" = { filename = "media-typer-npm-0.3.0-8674f8f0f5-af1b38516c.zip"; sha512 = "af1b38516c28ec95d6b0826f6c8f276c58aec391f76be42aa07646b4e39d317723e869700933ca6995b056db4b09a78c92d5440dc23657e6764be5d28874bba1"; };
"methods@npm:1.1.2" = { filename = "methods-npm-1.1.2-92f6fdb39b-0917ff4041.zip"; sha512 = "0917ff4041fa8e2f2fda5425a955fe16ca411591fbd123c0d722fcf02b73971ed6f764d85f0a6f547ce49ee0221ce2c19a5fa692157931cecb422984f1dcd13a"; };
"mime-db@npm:1.52.0" = { filename = "mime-db-npm-1.52.0-b5371d6fd2-0d99a03585.zip"; sha512 = "0d99a03585f8b39d68182803b12ac601d9c01abfa28ec56204fa330bc9f3d1c5e14beb049bafadb3dbdf646dfb94b87e24d4ec7b31b7279ef906a8ea9b6a513f"; };
"mime-types@npm:2.1.35" = { filename = "mime-types-npm-2.1.35-dd9ea9f3e2-89a5b7f1de.zip"; sha512 = "89a5b7f1def9f3af5dad6496c5ed50191ae4331cc5389d7c521c8ad28d5fdad2d06fd81baf38fed813dc4e46bb55c8145bb0ff406330818c9cf712fb2e9b3836"; };
"mimic-response@npm:2.1.0" = { filename = "mimic-response-npm-2.1.0-037463e454-014fad6ab9.zip"; sha512 = "014fad6ab936657e5f2f48bd87af62a8e928ebe84472aaf9e14fec4fcb31257a5edff77324d8ac13ddc6685ba5135cf16e381efac324e5f174fb4ddbf902bf07"; };
"mimic-response@npm:3.1.0" = { filename = "mimic-response-npm-3.1.0-a4a24b4e96-25739fee32.zip"; sha512 = "25739fee32c17f433626bf19f016df9036b75b3d84a3046c7d156e72ec963dd29d7fc8a302f55a3d6c5a4ff24259676b15d915aad6480815a969ff2ec0836867"; };
"mimic-response@npm:4.0.0" = { filename = "mimic-response-npm-4.0.0-c080547e26-33b804cc96.zip"; sha512 = "33b804cc961efe206efdb1fca6a22540decdcfce6c14eb5c0c50e5ae9022267ab22ce8f5568b1f7247ba67500fe20d523d81e0e9f009b321ccd9d472e78d1850"; };
"minimatch@npm:3.1.2" = { filename = "minimatch-npm-3.1.2-9405269906-c154e56640.zip"; sha512 = "c154e566406683e7bcb746e000b84d74465b3a832c45d59912b9b55cd50dee66e5c4b1e5566dba26154040e51672f9aa450a9aef0c97cfc7336b78b7afb9540a"; };
"minimatch@npm:5.0.1" = { filename = "minimatch-npm-5.0.1-612724f6f0-b34b98463d.zip"; sha512 = "b34b98463da4754bc526b244d680c69d4d6089451ebe512edaf6dd9eeed0279399cfa3edb19233513b8f830bf4bfcad911dddcdf125e75074100d52f724774f0"; };
"minimatch@npm:5.1.6" = { filename = "minimatch-npm-5.1.6-1e71429f4c-7564208ef8.zip"; sha512 = "7564208ef81d7065a370f788d337cd80a689e981042cb9a1d0e6580b6c6a8c9279eba80010516e258835a988363f99f54a6f711a315089b8b42694f5da9d0d77"; };
"minipass-collect@npm:1.0.2" = { filename = "minipass-collect-npm-1.0.2-3b4676eab5-14df761028.zip"; sha512 = "14df761028f3e47293aee72888f2657695ec66bd7d09cae7ad558da30415fdc4752bbfee66287dcc6fd5e6a2fa3466d6c484dc1cbd986525d9393b9523d97f10"; };
"minipass-fetch@npm:2.1.2" = { filename = "minipass-fetch-npm-2.1.2-9b21a5c930-3f216be791.zip"; sha512 = "3f216be79164e915fc91210cea1850e488793c740534985da017a4cbc7a5ff50506956d0f73bb0cb60e4fe91be08b6b61ef35101706d3ef5da2c8709b5f08f91"; };
"minipass-flush@npm:1.0.5" = { filename = "minipass-flush-npm-1.0.5-efe79d9826-56269a0b22.zip"; sha512 = "56269a0b22bad756a08a94b1ffc36b7c9c5de0735a4dd1ab2b06c066d795cfd1f0ac44a0fcae13eece5589b908ecddc867f04c745c7009be0b566421ea0944cf"; };
"minipass-pipeline@npm:1.2.4" = { filename = "minipass-pipeline-npm-1.2.4-5924cb077f-b14240dac0.zip"; sha512 = "b14240dac0d29823c3d5911c286069e36d0b81173d7bdf07a7e4a91ecdef92cdff4baaf31ea3746f1c61e0957f652e641223970870e2353593f382112257971b"; };
"minipass-sized@npm:1.0.3" = { filename = "minipass-sized-npm-1.0.3-306d86f432-79076749fc.zip"; sha512 = "79076749fcacf21b5d16dd596d32c3b6bf4d6e62abb43868fac21674078505c8b15eaca4e47ed844985a4514854f917d78f588fcd029693709417d8f98b2bd60"; };
"minipass@npm:3.3.6" = { filename = "minipass-npm-3.3.6-b8d93a945b-a30d083c80.zip"; sha512 = "a30d083c8054cee83cdcdc97f97e4641a3f58ae743970457b1489ce38ee1167b3aaf7d815cd39ec7a99b9c40397fd4f686e83750e73e652b21cb516f6d845e48"; };
"minipass@npm:4.0.3" = { filename = "minipass-npm-4.0.3-25515097a8-a09f405e2f.zip"; sha512 = "a09f405e2f380ae7f6ee0cbb53b45c1fcc1b6c70fc3896f4d20649d92a10e61892c57bd9960a64cedf6c90b50022cb6c195905b515039c335b423202f99e6f18"; };
"minizlib@npm:2.1.2" = { filename = "minizlib-npm-2.1.2-ea89cd0cfb-f1fdeac0b0.zip"; sha512 = "f1fdeac0b07cf8f30fcf12f4b586795b97be856edea22b5e9072707be51fc95d41487faec3f265b42973a304fe3a64acd91a44a3826a963e37b37bafde0212c3"; };
"mkdirp@npm:1.0.4" = { filename = "mkdirp-npm-1.0.4-37f6ef56b9-a96865108c.zip"; sha512 = "a96865108c6c3b1b8e1d5e9f11843de1e077e57737602de1b82030815f311be11f96f09cce59bd5b903d0b29834733e5313f9301e3ed6d6f6fba2eae0df4298f"; };
"mocha@npm:10.2.0" = { filename = "mocha-npm-10.2.0-87db25c7c5-406c45eab1.zip"; sha512 = "406c45eab122ffd6ea2003c2f108b2bc35ba036225eee78e0c784b6fa2c7f34e2b13f1dbacef55a4fdf523255d76e4f22d1b5aacda2394bd11666febec17c719"; };
"ms@npm:2.1.2" = { filename = "ms-npm-2.1.2-ec0c1512ff-673cdb2c31.zip"; sha512 = "673cdb2c3133eb050c745908d8ce632ed2c02d85640e2edb3ace856a2266a813b30c613569bf3354fdf4ea7d1a1494add3bfa95e2713baa27d0c2c71fc44f58f"; };
"ms@npm:2.1.3" = { filename = "ms-npm-2.1.3-81ff3cfac1-aa92de6080.zip"; sha512 = "aa92de608021b242401676e35cfa5aa42dd70cbdc082b916da7fb925c542173e36bce97ea3e804923fe92c0ad991434e4a38327e15a1b5b5f945d66df615ae6d"; };
"nan@npm:2.17.0" = { filename = "nan-npm-2.17.0-bf36a21d6f-ec609aeaf7.zip"; sha512 = "ec609aeaf7e68b76592a3ba96b372aa7f5df5b056c1e37410b0f1deefbab5a57a922061e2c5b369bae9c7c6b5e6eecf4ad2dac8833a1a7d3a751e0a7c7f849ed"; };
"nanoid@npm:3.3.3" = { filename = "nanoid-npm-3.3.3-25d865be84-ada019402a.zip"; sha512 = "ada019402a07464a694553c61d2dca8a4353645a7d92f2830f0d487fedff403678a0bee5323a46522752b2eab95a0bc3da98b6cccaa7c0c55cd9975130e6d6f0"; };
"negotiator@npm:0.6.3" = { filename = "negotiator-npm-0.6.3-9d50e36171-b8ffeb1e26.zip"; sha512 = "b8ffeb1e262eff7968fc90a2b6767b04cfd9842582a9d0ece0af7049537266e7b2506dfb1d107a32f06dd849ab2aea834d5830f7f4d0e5cb7d36e1ae55d021d9"; };
"node-domexception@npm:1.0.0" = { filename = "node-domexception-npm-1.0.0-e1e813b76f-ee1d37dd2a.zip"; sha512 = "ee1d37dd2a4eb26a8a92cd6b64dfc29caec72bff5e1ed9aba80c294f57a31ba4895a60fd48347cf17dd6e766da0ae87d75657dfd1f384ebfa60462c2283f5c7f"; };
"node-fetch@npm:2.6.9" = { filename = "node-fetch-npm-2.6.9-9fc9a54529-acb04f9ce7.zip"; sha512 = "acb04f9ce7224965b2b59e71b33c639794d8991efd73855b0b250921382b38331ffc9d61bce502571f6cc6e11a8905ca9b1b6d4aeb586ab093e2756a1fd190d0"; };
"node-fetch@npm:3.3.0" = { filename = "node-fetch-npm-3.3.0-45d971325c-e9936908d2.zip"; sha512 = "e9936908d2783d3c48a038e187f8062de294d75ef43ec8ab812d7cbd682be2b67605868758d2e9cad6103706dcfe4a9d21d78f6df984e8edf10e7a5ce2e665f8"; };
"node-gyp@npm:9.3.1" = { filename = "node-gyp-npm-9.3.1-43540bab9c-b860e9976f.zip"; sha512 = "b860e9976fa645ca0789c69e25387401b4396b93c8375489b5151a6c55cf2640a3b6183c212b38625ef7c508994930b72198338e3d09b9d7ade5acc4aaf51ea7"; };
"nopt@npm:5.0.0" = { filename = "nopt-npm-5.0.0-304b40fbfe-d35fdec187.zip"; sha512 = "d35fdec187269503843924e0114c0c6533fb54bbf1620d0f28b4b60ba01712d6687f62565c55cc20a504eff0fbe5c63e22340c3fad549ad40469ffb611b04f2f"; };
"nopt@npm:6.0.0" = { filename = "nopt-npm-6.0.0-5ea8050815-82149371f8.zip"; sha512 = "82149371f8be0c4b9ec2f863cc6509a7fd0fa729929c009f3a58e4eb0c9e4cae9920e8f1f8eb46e7d032fec8fb01bede7f0f41a67eb3553b7b8e14fa53de1dac"; };
"normalize-path@npm:3.0.0" = { filename = "normalize-path-npm-3.0.0-658ba7d77f-88eeb4da89.zip"; sha512 = "88eeb4da891e10b1318c4b2476b6e2ecbeb5ff97d946815ffea7794c31a89017c70d7f34b3c2ebf23ef4e9fc9fb99f7dffe36da22011b5b5c6ffa34f4873ec20"; };
"normalize-url@npm:8.0.0" = { filename = "normalize-url-npm-8.0.0-1f5dc7ece5-24c20b75eb.zip"; sha512 = "24c20b75ebfd526d8453084692720b49d111c63c0911f1b7447427829597841eef5a8ba3f6bb93d6654007b991c1f5cd85da2c907800e439e2e2ec6c2abd0fc0"; };
"npmlog@npm:5.0.1" = { filename = "npmlog-npm-5.0.1-366cab64a2-516b266302.zip"; sha512 = "516b2663028761f062d13e8beb3f00069c5664925871a9b57989642ebe09f23ab02145bf3ab88da7866c4e112cafff72401f61a672c7c8a20edc585a7016ef5f"; };
"npmlog@npm:6.0.2" = { filename = "npmlog-npm-6.0.2-e0e69455c7-ae238cd264.zip"; sha512 = "ae238cd264a1c3f22091cdd9e2b106f684297d3c184f1146984ecbe18aaa86343953f26b9520dedd1b1372bc0316905b736c1932d778dbeb1fcf5a1001390e2a"; };
"object-assign@npm:4.1.1" = { filename = "object-assign-npm-4.1.1-1004ad6dec-fcc6e4ea8c.zip"; sha512 = "fcc6e4ea8c7fe48abfbb552578b1c53e0d194086e2e6bbbf59e0a536381a292f39943c6e9628af05b5528aa5e3318bb30d6b2e53cadaf5b8fe9e12c4b69af23f"; };
"object-inspect@npm:1.12.3" = { filename = "object-inspect-npm-1.12.3-1e7d20f5ff-dabfd824d9.zip"; sha512 = "dabfd824d97a5f407e6d5d24810d888859f6be394d8b733a77442b277e0808860555176719c5905e765e3743a7cada6b8b0a3b85e5331c530fd418cc8ae991db"; };
"on-finished@npm:2.4.1" = { filename = "on-finished-npm-2.4.1-907af70f88-d20929a25e.zip"; sha512 = "d20929a25e7f0bb62f937a425b5edeb4e4cde0540d77ba146ec9357f00b0d497cdb3b9b05b9c8e46222407d1548d08166bff69cc56dfa55ba0e4469228920ff0"; };
"once@npm:1.4.0" = { filename = "once-npm-1.4.0-ccf03ef07a-cd0a885013.zip"; sha512 = "cd0a88501333edd640d95f0d2700fbde6bff20b3d4d9bdc521bdd31af0656b5706570d6c6afe532045a20bb8dc0849f8332d6f2a416e0ba6d3d3b98806c7db68"; };
"only@npm:0.0.2" = { filename = "only-npm-0.0.2-122402a3f9-d399710db8.zip"; sha512 = "d399710db867a1ef436dd3ce74499c87ece794aa81ab0370b5d153968766ee4aed2f98d3f92fc87c963e45b7a74d400d6f463ef651a5e7cfb861b15e88e9efe6"; };
"p-cancelable@npm:3.0.0" = { filename = "p-cancelable-npm-3.0.0-e6c8101c97-2b5ae34218.zip"; sha512 = "2b5ae34218f9c2cf7a7c18e5d9a726ef9b165ef07e6c959f6738371509e747334b5f78f3bcdeb03d8a12dcb978faf641fd87eb21486ed7d36fb823b8ddef3219"; };
"p-limit@npm:3.1.0" = { filename = "p-limit-npm-3.1.0-05d2ede37f-7c3690c4db.zip"; sha512 = "7c3690c4dbf62ef625671e20b7bdf1cbc9534e83352a2780f165b0d3ceba21907e77ad63401708145ca4e25bfc51636588d89a8c0aeb715e6c37d1c066430360"; };
"p-locate@npm:5.0.0" = { filename = "p-locate-npm-5.0.0-92cc7c7a3e-1623088f36.zip"; sha512 = "1623088f36cf1cbca58e9b61c4e62bf0c60a07af5ae1ca99a720837356b5b6c5ba3eb1b2127e47a06865fee59dd0453cad7cc844cda9d5a62ac1a5a51b7c86d3"; };
"p-map@npm:4.0.0" = { filename = "p-map-npm-4.0.0-4677ae07c7-cb0ab21ec0.zip"; sha512 = "cb0ab21ec0f32ddffd31dfc250e3afa61e103ef43d957cc45497afe37513634589316de4eb88abdfd969fe6410c22c0b93ab24328833b8eb1ccc087fc0442a1c"; };
"packet-reader@npm:1.0.0" = { filename = "packet-reader-npm-1.0.0-e93c92246b-0b7516f0cb.zip"; sha512 = "0b7516f0cbf3e322aad591bed29ba544220088c53943145c0d9121a6f59182ad811f7fd6785a8979a34356aca69d97653689029964c5998dc02645633d88ffd7"; };
"parse5@npm:7.1.2" = { filename = "parse5-npm-7.1.2-aa9a92c270-59465dd05e.zip"; sha512 = "59465dd05eb4c5ec87b76173d1c596e152a10e290b7abcda1aecf0f33be49646ea74840c69af975d7887543ea45564801736356c568d6b5e71792fd0f4055713"; };
"parseurl@npm:1.3.3" = { filename = "parseurl-npm-1.3.3-1542397e00-407cee8e0a.zip"; sha512 = "407cee8e0a3a4c5cd472559bca8b6a45b82c124e9a4703302326e9ab60fc1081442ada4e02628efef1eb16197ddc7f8822f5a91fd7d7c86b51f530aedb17dfa2"; };
"path-exists@npm:4.0.0" = { filename = "path-exists-npm-4.0.0-e9e4f63eb0-505807199d.zip"; sha512 = "505807199dfb7c50737b057dd8d351b82c033029ab94cb10a657609e00c1bc53b951cfdbccab8de04c5584d5eff31128ce6afd3db79281874a5ef2adbba55ed1"; };
"path-is-absolute@npm:1.0.1" = { filename = "path-is-absolute-npm-1.0.1-31bc695ffd-060840f92c.zip"; sha512 = "060840f92cf8effa293bcc1bea81281bd7d363731d214cbe5c227df207c34cd727430f70c6037b5159c8a870b9157cba65e775446b0ab06fd5ecc7e54615a3b8"; };
"path-to-regexp@npm:6.2.1" = { filename = "path-to-regexp-npm-6.2.1-8ebfe03654-f0227af828.zip"; sha512 = "f0227af8284ea13300f4293ba111e3635142f976d4197f14d5ad1f124aebd9118783dd2e5f1fe16f7273743cc3dbeddfb7493f237bb27c10fdae07020cc9b698"; };
"pathval@npm:1.1.1" = { filename = "pathval-npm-1.1.1-ce0311d7e0-090e314771.zip"; sha512 = "090e3147716647fb7fb5b4b8c8e5b55e5d0a6086d085b6cd23f3d3c01fcf0ff56fd3cc22f2f4a033bd2e46ed55d61ed8379e123b42afe7d531a2a5fc8bb556d6"; };
"pg-connection-string@npm:2.5.0" = { filename = "pg-connection-string-npm-2.5.0-1ee5de9ab9-a6f3a068f7.zip"; sha512 = "a6f3a068f7c9416a5b33a326811caf0dfaaee045c225b7c628b4c9b4e9a2b25bdd12a21e4c48940e1000ea223a4e608ca122d2ff3dd08c8b1db0fc9f5705133a"; };
"pg-int8@npm:1.0.1" = { filename = "pg-int8-npm-1.0.1-5cd67f3e22-a1e3a05a69.zip"; sha512 = "a1e3a05a69005ddb73e5f324b6b4e689868a447c5fa280b44cd4d04e6916a344ac289e0b8d2695d66e8e89a7fba023affb9e0e94778770ada5df43f003d664c9"; };
"pg-pool@npm:3.5.2" = { filename = "pg-pool-npm-3.5.2-d467bbecca-a5d0292002.zip"; sha512 = "a5d029200257671f0c17ca54b9ab6213e2060e64e5cc792b78edd50ab471a26cd364890d05d546d9296949e079e943821cf2ceb4d488f4e6a6789fb781a628bf"; };
"pg-protocol@npm:1.6.0" = { filename = "pg-protocol-npm-1.6.0-089a4b1d3c-e12662d2de.zip"; sha512 = "e12662d2de2011e0c3a03f6a09f435beb1025acdc860f181f18a600a5495dc38a69d753bbde1ace279c8c442536af9c1a7c11e1d0fe3fad3aa1348b28d9d2683"; };
"pg-types@npm:2.2.0" = { filename = "pg-types-npm-2.2.0-a3360226c4-bf4ec3f594.zip"; sha512 = "bf4ec3f594743442857fb3a8dfe5d2478a04c98f96a0a47365014557cbc0b4b0cee01462c79adca863b93befbf88f876299b75b72c665b5fb84a2c94fbd10316"; };
"pg@npm:8.9.0" = { filename = "pg-npm-8.9.0-af609b947e-dfd1589553.zip"; sha512 = "dfd158955318f9ffb9428eaada29f3ee98b9eb07e87ed4b56589a19984d109f23bb8f88db78b7d7f870553e5b75ca0d58d0ed55755a8c6aed5df44e038c1d529"; };
"pgpass@npm:1.0.5" = { filename = "pgpass-npm-1.0.5-653e71ddd8-947ac096c0.zip"; sha512 = "947ac096c031eebdf08d989de2e9f6f156b8133d6858c7c2c06c041e1e71dda6f5f3bad3c0ec1e96a09497bbc6ef89e762eefe703b5ef9cb2804392ec52ec400"; };
"picomatch@npm:2.3.1" = { filename = "picomatch-npm-2.3.1-c782cfd986-050c865ce8.zip"; sha512 = "050c865ce81119c4822c45d3c84f1ced46f93a0126febae20737bd05ca20589c564d6e9226977df859ed5e03dc73f02584a2b0faad36e896936238238b0446cf"; };
"postgres-array@npm:2.0.0" = { filename = "postgres-array-npm-2.0.0-4f49dc1389-0e1e659888.zip"; sha512 = "0e1e659888147c5de579d229a2d95c0d83ebdbffc2b9396d890a123557708c3b758a0a97ed305ce7f58edfa961fa9f0bbcd1ea9f08b6e5df73322e683883c464"; };
"postgres-bytea@npm:1.0.0" = { filename = "postgres-bytea-npm-1.0.0-8c2b81fa73-d844ae4ca7.zip"; sha512 = "d844ae4ca7a941b70e45cac1261a73ee8ed39d72d3d74ab1d645248185a1b7f0ac91a3c63d6159441020f4e1f7fe64689ac56536a307b31cef361e5187335090"; };
"postgres-date@npm:1.0.7" = { filename = "postgres-date-npm-1.0.7-aadfe5531e-5745001d47.zip"; sha512 = "5745001d47e51cd767e46bcb1710649cd705d91a24d42fa661c454b6dcbb7353c066a5047983c90a626cd3bbfea9e626cc6fa84a35ec57e5bbb28b49f78e13ed"; };
"postgres-interval@npm:1.2.0" = { filename = "postgres-interval-npm-1.2.0-ca6414744d-746b71f938.zip"; sha512 = "746b71f93805ae33b03528e429dc624706d1f9b20ee81bf743263efb6a0cd79ae02a642a8a480dbc0f09547b4315ab7df6ce5ec0be77ed700bac42730f5c76b2"; };
"prettier@npm:2.8.3" = { filename = "prettier-npm-2.8.3-2c5624c4ca-92f2ceb522.zip"; sha512 = "92f2ceb522d454370e02082aa74ad27388672f7cee8975028b59517c069fe643bdc73e322675c8faf2ff173d7a626d1a6389f26b474000308e793aa25fff46e5"; };
"promise-inflight@npm:1.0.1" = { filename = "promise-inflight-npm-1.0.1-5bb925afac-2274948309.zip"; sha512 = "22749483091d2c594261517f4f80e05226d4d5ecc1fc917e1886929da56e22b5718b7f2a75f3807e7a7d471bc3be2907fe92e6e8f373ddf5c64bae35b5af3981"; };
"promise-retry@npm:2.0.1" = { filename = "promise-retry-npm-2.0.1-871f0b01b7-f96a3f6d90.zip"; sha512 = "f96a3f6d90b92b568a26f71e966cbbc0f63ab85ea6ff6c81284dc869b41510e6cdef99b6b65f9030f0db422bf7c96652a3fff9f2e8fb4a0f069d8f4430359429"; };
"qs@npm:6.11.0" = { filename = "qs-npm-6.11.0-caf1bc9dea-6e1f29dd53.zip"; sha512 = "6e1f29dd5385f7488ec74ac7b6c92f4d09a90408882d0c208414a34dd33badc1a621019d4c799a3df15ab9b1d0292f97c1dd71dc7c045e69f81a8064e5af7297"; };
"quick-lru@npm:5.1.1" = { filename = "quick-lru-npm-5.1.1-e38e0edce3-a516faa255.zip"; sha512 = "a516faa25574be7947969883e6068dbe4aa19e8ef8e8e0fd96cddd6d36485e9106d85c0041a27153286b0770b381328f4072aa40d3b18a19f5f7d2b78b94b5ed"; };
"randombytes@npm:2.1.0" = { filename = "randombytes-npm-2.1.0-e3da76bccf-d779499376.zip"; sha512 = "d779499376bd4cbb435ef3ab9a957006c8682f343f14089ed5f27764e4645114196e75b7f6abf1cbd84fd247c0cb0651698444df8c9bf30e62120fbbc52269d6"; };
"raw-body@npm:2.5.1" = { filename = "raw-body-npm-2.5.1-9dd1d9fff9-5362adff15.zip"; sha512 = "5362adff1575d691bb3f75998803a0ffed8c64eabeaa06e54b4ada25a0cd1b2ae7f4f5ec46565d1bec337e08b5ac90c76eaa0758de6f72a633f025d754dec29e"; };
"rdf-canonize@npm:3.3.0" = { filename = "rdf-canonize-npm-3.3.0-8e9fece515-4aa4ac59e6.zip"; sha512 = "4aa4ac59e6ab0bed25cf95fc7f247537507d3f2b2d0742a48dd12a8f2ebc809c0863858f15c73fb8d13f1efe332e4961f7be62fdda9a0abb75d97178410c8cd5"; };
"readable-stream@npm:3.6.0" = { filename = "readable-stream-npm-3.6.0-23a4a5eb56-d4ea81502d.zip"; sha512 = "d4ea81502d3799439bb955a3a5d1d808592cf3133350ed352aeaa499647858b27b1c4013984900238b0873ec8d0d8defce72469fb7a83e61d53f5ad61cb80dc8"; };
"readdirp@npm:3.6.0" = { filename = "readdirp-npm-3.6.0-f950cc74ab-1ced032e6e.zip"; sha512 = "1ced032e6e45670b6d7352d71d21ce7edf7b9b928494dcaba6f11fba63180d9da6cd7061ebc34175ffda6ff529f481818c962952004d273178acd70f7059b320"; };
"require-directory@npm:2.1.1" = { filename = "require-directory-npm-2.1.1-8608aee50b-fb47e70bf0.zip"; sha512 = "fb47e70bf0001fdeabdc0429d431863e9475e7e43ea5f94ad86503d918423c1543361cc5166d713eaa7029dd7a3d34775af04764bebff99ef413111a5af18c80"; };
"resolve-alpn@npm:1.2.1" = { filename = "resolve-alpn-npm-1.2.1-af77edd28b-f558071fcb.zip"; sha512 = "f558071fcb2c60b04054c99aebd572a2af97ef64128d59bef7ab73bd50d896a222a056de40ffc545b633d99b304c259ea9d0c06830d5c867c34f0bfa60b8eae0"; };
"responselike@npm:3.0.0" = { filename = "responselike-npm-3.0.0-9ab07af81f-e0cc9be30d.zip"; sha512 = "e0cc9be30df4f415d6d83cdede3c5c887cd4a73e7cc1708bcaab1d50a28d15acb68460ac5b02bcc55a42f3d493729c8856427dcf6e57e6e128ad05cba4cfb95e"; };
"retry@npm:0.12.0" = { filename = "retry-npm-0.12.0-72ac7fb4cc-623bd7d2e5.zip"; sha512 = "623bd7d2e5119467ba66202d733ec3c2e2e26568074923bc0585b6b99db14f357e79bdedb63cab56cec47491c4a0da7e6021a7465ca6dc4f481d3898fdd3158c"; };
"rimraf@npm:3.0.2" = { filename = "rimraf-npm-3.0.2-2cb7dac69a-87f4164e39.zip"; sha512 = "87f4164e396f0171b0a3386cc1877a817f572148ee13a7e113b238e48e8a9f2f31d009a92ec38a591ff1567d9662c6b67fd8818a2dbbaed74bc26a87a2a4a9a0"; };
"safe-buffer@npm:5.2.1" = { filename = "safe-buffer-npm-5.2.1-3481c8aa9b-b99c4b41fd.zip"; sha512 = "b99c4b41fdd67a6aaf280fcd05e9ffb0813654894223afb78a31f14a19ad220bba8aba1cb14eddce1fcfb037155fe6de4e861784eb434f7d11ed58d1e70dd491"; };
"safer-buffer@npm:2.1.2" = { filename = "safer-buffer-npm-2.1.2-8d5c0b705e-cab8f25ae6.zip"; sha512 = "cab8f25ae6f1434abee8d80023d7e72b598cf1327164ddab31003c51215526801e40b66c5e65d658a0af1e9d6478cadcb4c745f4bd6751f97d8644786c0978b0"; };
"semver@npm:6.3.0" = { filename = "semver-npm-6.3.0-b3eace8bfd-1b26ecf6db.zip"; sha512 = "1b26ecf6db9e8292dd90df4e781d91875c0dcc1b1909e70f5d12959a23c7eebb8f01ea581c00783bbee72ceeaad9505797c381756326073850dc36ed284b21b9"; };
"semver@npm:7.3.8" = { filename = "semver-npm-7.3.8-25a996cb4f-ba9c7cbbf2.zip"; sha512 = "ba9c7cbbf2b7884696523450a61fee1a09930d888b7a8d7579025ad93d459b2d1949ee5bbfeb188b2be5f4ac163544c5e98491ad6152df34154feebc2cc337c1"; };
"serialize-javascript@npm:6.0.0" = { filename = "serialize-javascript-npm-6.0.0-0bb8a3c88d-56f90b562a.zip"; sha512 = "56f90b562a1bdc92e55afb3e657c6397c01a902c588c0fe3d4c490efdcc97dcd2a3074ba12df9e94630f33a5ce5b76a74784a7041294628a6f4306e0ec84bf93"; };
"set-blocking@npm:2.0.0" = { filename = "set-blocking-npm-2.0.0-49e2cffa24-6e65a05f7c.zip"; sha512 = "6e65a05f7cf7ebdf8b7c75b101e18c0b7e3dff4940d480efed8aad3a36a4005140b660fa1d804cb8bce911cac290441dc728084a30504d3516ac2ff7ad607b02"; };
"setimmediate@npm:1.0.5" = { filename = "setimmediate-npm-1.0.5-54587459b6-c9a6f2c5b5.zip"; sha512 = "c9a6f2c5b51a2dabdc0247db9c46460152ffc62ee139f3157440bd48e7c59425093f42719ac1d7931f054f153e2d26cf37dfeb8da17a794a58198a2705e527fd"; };
"setprototypeof@npm:1.2.0" = { filename = "setprototypeof-npm-1.2.0-0fedbdcd3a-be18cbbf70.zip"; sha512 = "be18cbbf70e7d8097c97f713a2e76edf84e87299b40d085c6bf8b65314e994cc15e2e317727342fa6996e38e1f52c59720b53fe621e2eb593a6847bf0356db89"; };
"side-channel@npm:1.0.4" = { filename = "side-channel-npm-1.0.4-e1f38b9e06-351e41b947.zip"; sha512 = "351e41b947079c10bd0858364f32bb3a7379514c399edb64ab3dce683933483fc63fb5e4efe0a15a2e8a7e3c436b6a91736ddb8d8c6591b0460a24bb4a1ee245"; };
"signal-exit@npm:3.0.7" = { filename = "signal-exit-npm-3.0.7-bd270458a3-a2f098f247.zip"; sha512 = "a2f098f247adc367dffc27845853e9959b9e88b01cb301658cfe4194352d8d2bb32e18467c786a7fe15f1d44b233ea35633d076d5e737870b7139949d1ab6318"; };
"simple-concat@npm:1.0.1" = { filename = "simple-concat-npm-1.0.1-48df70de29-4d211042cc.zip"; sha512 = "4d211042cc3d73a718c21ac6c4e7d7a0363e184be6a5ad25c8a1502e49df6d0a0253979e3d50dbdd3f60ef6c6c58d756b5d66ac1e05cda9cacd2e9fc59e3876a"; };
"simple-get@npm:3.1.1" = { filename = "simple-get-npm-3.1.1-dce5923dba-80195e70bf.zip"; sha512 = "80195e70bf171486e75c31e28e5485468195cc42f85940f8b45c4a68472160144d223eb4d07bc82ef80cb974b7c401db021a540deb2d34ac4b3b8883da2d6401"; };
"smart-buffer@npm:4.2.0" = { filename = "smart-buffer-npm-4.2.0-5ac3f668bb-b5167a7142.zip"; sha512 = "b5167a7142c1da704c0e3af85c402002b597081dd9575031a90b4f229ca5678e9a36e8a374f1814c8156a725d17008ae3bde63b92f9cfd132526379e580bec8b"; };
"socks-proxy-agent@npm:7.0.0" = { filename = "socks-proxy-agent-npm-7.0.0-7aacf32ea0-7205543701.zip"; sha512 = "720554370154cbc979e2e9ce6a6ec6ced205d02757d8f5d93fe95adae454fc187a5cbfc6b022afab850a5ce9b4c7d73e0f98e381879cf45f66317a4895953846"; };
"socks@npm:2.7.1" = { filename = "socks-npm-2.7.1-17f2b53052-259d9e3e8e.zip"; sha512 = "259d9e3e8e1c9809a7f5c32238c3d4d2a36b39b83851d0f573bfde5f21c4b1288417ce1af06af1452569cd1eb0841169afd4998f0e04ba04656f6b7f0e46d748"; };
"split2@npm:4.1.0" = { filename = "split2-npm-4.1.0-1c1a4bd984-ec581597cb.zip"; sha512 = "ec581597cb74c13cdfb5e2047543dd40cb1e8e9803c7b1e0c29ede05f2b4f049b2d6e7f2788a225d544549375719658b8f38e9366364dec35dc7a12edfda5ee5"; };
"ssri@npm:9.0.1" = { filename = "ssri-npm-9.0.1-33ce27f4f8-fb58f5e46b.zip"; sha512 = "fb58f5e46b6923ae67b87ad5ef1c5ab6d427a17db0bead84570c2df3cd50b4ceb880ebdba2d60726588272890bae842a744e1ecce5bd2a2a582fccd5068309eb"; };
"statuses@npm:1.5.0" = { filename = "statuses-npm-1.5.0-f88f91b2e9-c469b9519d.zip"; sha512 = "c469b9519de16a4bb19600205cffb39ee471a5f17b82589757ca7bd40a8d92ebb6ed9f98b5a540c5d302ccbc78f15dc03cc0280dd6e00df1335568a5d5758a5c"; };
"statuses@npm:2.0.1" = { filename = "statuses-npm-2.0.1-81d2b97fee-18c7623fdb.zip"; sha512 = "18c7623fdb8f646fb213ca4051be4df7efb3484d4ab662937ca6fbef7ced9b9e12842709872eb3020cc3504b93bde88935c9f6417489627a7786f24f8031cbcb"; };
"streamsearch@npm:1.1.0" = { filename = "streamsearch-npm-1.1.0-fc3ad6536d-1cce16cea8.zip"; sha512 = "1cce16cea8405d7a233d32ca5e00a00169cc0e19fbc02aa839959985f267335d435c07f96e5e0edd0eadc6d39c98d5435fb5bbbdefc62c41834eadc5622ad942"; };
"string-width@npm:4.2.3" = { filename = "string-width-npm-4.2.3-2c27177bae-e52c10dc3f.zip"; sha512 = "e52c10dc3fbfcd6c3a15f159f54a90024241d0f149cf8aed2982a2d801d2e64df0bf1dc351cf8e95c3319323f9f220c16e740b06faecd53e2462df1d2b5443fb"; };
"string_decoder@npm:1.3.0" = { filename = "string_decoder-npm-1.3.0-2422117fd0-8417646695.zip"; sha512 = "8417646695a66e73aefc4420eb3b84cc9ffd89572861fe004e6aeb13c7bc00e2f616247505d2dbbef24247c372f70268f594af7126f43548565c68c117bdeb56"; };
"strip-ansi@npm:6.0.1" = { filename = "strip-ansi-npm-6.0.1-caddc7cb40-f3cd25890a.zip"; sha512 = "f3cd25890aef3ba6e1a74e20896c21a46f482e93df4a06567cebf2b57edabb15133f1f94e57434e0a958d61186087b1008e89c94875d019910a213181a14fc8c"; };
"strip-json-comments@npm:3.1.1" = { filename = "strip-json-comments-npm-3.1.1-dcb2324823-492f73e272.zip"; sha512 = "492f73e27268f9b1c122733f28ecb0e7e8d8a531a6662efbd08e22cccb3f9475e90a1b82cab06a392f6afae6d2de636f977e231296400d0ec5304ba70f166443"; };
"supports-color@npm:7.2.0" = { filename = "supports-color-npm-7.2.0-606bfcf7da-3dda818de0.zip"; sha512 = "3dda818de06ebbe5b9653e07842d9479f3555ebc77e9a0280caf5a14fb877ffee9ed57007c3b78f5a6324b8dbeec648d9e97a24e2ed9fdb81ddc69ea07100f4a"; };
"supports-color@npm:8.1.1" = { filename = "supports-color-npm-8.1.1-289e937149-c052193a7e.zip"; sha512 = "c052193a7e43c6cdc741eb7f378df605636e01ad434badf7324f17fb60c69a880d8d8fcdcb562cf94c2350e57b937d7425ab5b8326c67c2adc48f7c87c1db406"; };
"tar@npm:6.1.13" = { filename = "tar-npm-6.1.13-3234e72781-8a278bed12.zip"; sha512 = "8a278bed123aa9f53549b256a36b719e317c8b96fe86a63406f3c62887f78267cea9b22dc6f7007009738509800d4a4dccc444abd71d762287c90f35b002eb1c"; };
"to-regex-range@npm:5.0.1" = { filename = "to-regex-range-npm-5.0.1-f1e8263b00-f76fa01b3d.zip"; sha512 = "f76fa01b3d5be85db6a2a143e24df9f60dd047d151062d0ba3df62953f2f697b16fe5dad9b0ac6191c7efc7b1d9dcaa4b768174b7b29da89d4428e64bc0a20ed"; };
"toidentifier@npm:1.0.1" = { filename = "toidentifier-npm-1.0.1-f759712599-952c29e2a8.zip"; sha512 = "952c29e2a85d7123239b5cfdd889a0dde47ab0497f0913d70588f19c53f7e0b5327c95f4651e413c74b785147f9637b17410ac8c846d5d4a20a5a33eb6dc3a45"; };
"tr46@npm:0.0.3" = { filename = "tr46-npm-0.0.3-de53018915-726321c5ea.zip"; sha512 = "726321c5eaf41b5002e17ffbd1fb7245999a073e8979085dacd47c4b4e8068ff5777142fc6726d6ca1fd2ff16921b48788b87225cbc57c72636f6efa8efbffe3"; };
"tsscmp@npm:1.0.6" = { filename = "tsscmp-npm-1.0.6-3223087558-1512384def.zip"; sha512 = "1512384def36bccc9125cabbd4c3b0e68608d7ee08127ceaa0b84a71797263f1a01c7f82fa69be8a3bd3c1396e2965d2f7b52d581d3a5eeaf3967fbc52e3b3bf"; };
"type-detect@npm:4.0.8" = { filename = "type-detect-npm-4.0.8-8d8127b901-62b5628bff.zip"; sha512 = "62b5628bff67c0eb0b66afa371bd73e230399a8d2ad30d852716efcc4656a7516904570cd8631a49a3ce57c10225adf5d0cbdcb47f6b0255fe6557c453925a15"; };
"type-is@npm:1.6.18" = { filename = "type-is-npm-1.6.18-6dee4d4961-2c8e47675d.zip"; sha512 = "2c8e47675d55f8b4e404bcf529abdf5036c537a04c2b20177bcf78c9e3c1da69da3942b1346e6edb09e823228c0ee656ef0e033765ec39a70d496ef601a0c657"; };
"typescript@npm:4.9.5" = { filename = "typescript-npm-4.9.5-6427b65ee6-ee000bc268.zip"; sha512 = "ee000bc26848147ad423b581bd250075662a354d84f0e06eb76d3b892328d8d4440b7487b5a83e851b12b255f55d71835b008a66cbf8f255a11e4400159237db"; };
"typescript@patch:typescript@npm%3A4.9.5#~builtin<compat/typescript>::version=4.9.5&hash=23ec76" = { filename = "typescript-patch-72dc6f164f-ab417a2f39.zip"; sha512 = "ab417a2f398380c90a6cf5a5f74badd17866adf57f1165617d6a551f059c3ba0a3e4da0d147b3ac5681db9ac76a303c5876394b13b3de75fdd5b1eaa06181c9d"; };
"undici@npm:5.18.0" = { filename = "undici-npm-5.18.0-4aed233374-74e0f357c3.zip"; sha512 = "74e0f357c376c745fcca612481a5742866ae36086ad387e626255f4c4a15fc5357d9d0fa4355271b6a633d50f5556c3e85720844680c44861c66e23afca7245f"; };
"unique-filename@npm:2.0.1" = { filename = "unique-filename-npm-2.0.1-183c6c7c2b-807acf3381.zip"; sha512 = "807acf3381aff319086b64dc7125a9a37c09c44af7620bd4f7f3247fcd5565660ac12d8b80534dcbfd067e6fe88a67e621386dd796a8af828d1337a8420a255f"; };
"unique-slug@npm:3.0.0" = { filename = "unique-slug-npm-3.0.0-0b82e51577-49f8d915ba.zip"; sha512 = "49f8d915ba7f0101801b922062ee46b7953256c93ceca74303bd8e6413ae10aa7e8216556b54dc5382895e8221d04f1efaf75f945c2e4a515b4139f77aa6640c"; };
"unpipe@npm:1.0.0" = { filename = "unpipe-npm-1.0.0-2ed2a3c2bf-4fa18d8d8d.zip"; sha512 = "4fa18d8d8d977c55cb09715385c203197105e10a6d220087ec819f50cb68870f02942244f1017565484237f1f8c5d3cd413631b1ae104d3096f24fdfde1b4aa2"; };
"util-deprecate@npm:1.0.2" = { filename = "util-deprecate-npm-1.0.2-e3fe1a219c-474acf1146.zip"; sha512 = "474acf1146cb2701fe3b074892217553dfcf9a031280919ba1b8d651a068c9b15d863b7303cb15bd00a862b498e6cf4ad7b4a08fb134edd5a6f7641681cb54a2"; };
"uuid@npm:9.0.0" = { filename = "uuid-npm-9.0.0-46c41e3e43-8dd2c83c43.zip"; sha512 = "8dd2c83c43ddc7e1c71e36b60aea40030a6505139af6bee0f382ebcd1a56f6cd3028f7f06ffb07f8cf6ced320b76aea275284b224b002b289f89fe89c389b028"; };
"vary@npm:1.1.2" = { filename = "vary-npm-1.1.2-b49f70ae63-ae0123222c.zip"; sha512 = "ae0123222c6df65b437669d63dfa8c36cee20a504101b2fcd97b8bf76f91259c17f9f2b4d70a1e3c6bbcee7f51b28392833adb6b2770b23b01abec84e369660b"; };
"web-streams-polyfill@npm:3.2.1" = { filename = "web-streams-polyfill-npm-3.2.1-835bd3857e-b119c78574.zip"; sha512 = "b119c78574b6d65935e35098c2afdcd752b84268e18746606af149e3c424e15621b6f1ff0b42b2676dc012fc4f0d313f964b41a4b5031e525faa03997457da02"; };
"webidl-conversions@npm:3.0.1" = { filename = "webidl-conversions-npm-3.0.1-60310f6a2b-c92a0a6ab9.zip"; sha512 = "c92a0a6ab95314bde9c32e1d0a6dfac83b578f8fa5f21e675bc2706ed6981bc26b7eb7e6a1fab158e5ce4adf9caa4a0aee49a52505d4d13c7be545f15021b17c"; };
"whatwg-url@npm:5.0.0" = { filename = "whatwg-url-npm-5.0.0-374fb45e60-b8daed4ad3.zip"; sha512 = "b8daed4ad3356cc4899048a15b2c143a9aed0dfae1f611ebd55073310c7b910f522ad75d727346ad64203d7e6c79ef25eafd465f4d12775ca44b90fa82ed9e2c"; };
"which@npm:2.0.2" = { filename = "which-npm-2.0.2-320ddf72f7-1a5c563d3c.zip"; sha512 = "1a5c563d3c1b52d5f893c8b61afe11abc3bab4afac492e8da5bde69d550de701cf9806235f20a47b5c8fa8a1d6a9135841de2596535e998027a54589000e66d1"; };
"wide-align@npm:1.1.5" = { filename = "wide-align-npm-1.1.5-889d77e592-d5fc37cd56.zip"; sha512 = "d5fc37cd561f9daee3c80e03b92ed3e84d80dde3365a8767263d03dacfc8fa06b065ffe1df00d8c2a09f731482fcacae745abfbb478d4af36d0a891fad4834d3"; };
"workerpool@npm:6.2.1" = { filename = "workerpool-npm-6.2.1-1486cb2056-c2c6eebbc5.zip"; sha512 = "c2c6eebbc5225f10f758d599a5c016fa04798bcc44e4c1dffb34050cd361d7be2e97891aa44419e7afe647b1f767b1dc0b85a5e046c409d890163f655028b09d"; };
"wrap-ansi@npm:7.0.0" = { filename = "wrap-ansi-npm-7.0.0-ad6e1a0554-a790b846fd.zip"; sha512 = "a790b846fd4505de962ba728a21aaeda189b8ee1c7568ca5e817d85930e06ef8d1689d49dbf0e881e8ef84436af3a88bc49115c2e2788d841ff1b8b5b51a608b"; };
"wrappy@npm:1.0.2" = { filename = "wrappy-npm-1.0.2-916de4d4b3-159da4805f.zip"; sha512 = "159da4805f7e84a3d003d8841557196034155008f817172d4e986bd591f74aa82aa7db55929a54222309e01079a65a92a9e6414da5a6aa4b01ee44a511ac3ee5"; };
"xtend@npm:4.0.2" = { filename = "xtend-npm-4.0.2-7f2375736e-ac5dfa738b.zip"; sha512 = "ac5dfa738b21f6e7f0dd6e65e1b3155036d68104e67e5d5d1bde74892e327d7e5636a076f625599dc394330a731861e87343ff184b0047fef1360a7ec0a5a36a"; };
"y18n@npm:5.0.8" = { filename = "y18n-npm-5.0.8-5f3a0a7e62-54f0fb9562.zip"; sha512 = "54f0fb95621ee60898a38c572c515659e51cc9d9f787fb109cef6fde4befbe1c4602dc999d30110feee37456ad0f1660fa2edcfde6a9a740f86a290999550d30"; };
"yallist@npm:4.0.0" = { filename = "yallist-npm-4.0.0-b493d9e907-343617202a.zip"; sha512 = "343617202af32df2a15a3be36a5a8c0c8545208f3d3dfbc6bb7c3e3b7e8c6f8e7485432e4f3b88da3031a6e20afa7c711eded32ddfb122896ac5d914e75848d5"; };
"yargs-parser@npm:20.2.4" = { filename = "yargs-parser-npm-20.2.4-1de20916a6-d251998a37.zip"; sha512 = "d251998a374b2743a20271c2fd752b9fbef24eb881d53a3b99a7caa5e8227fcafd9abf1f345ac5de46435821be25ec12189a11030c12ee6481fef6863ed8b924"; };
"yargs-parser@npm:20.2.9" = { filename = "yargs-parser-npm-20.2.9-a1d19e598d-8bb69015f2.zip"; sha512 = "8bb69015f2b0ff9e17b2c8e6bfe224ab463dd00ca211eece72a4cd8a906224d2703fb8a326d36fdd0e68701e201b2a60ed7cf81ce0fd9b3799f9fe7745977ae3"; };
"yargs-unparser@npm:2.0.0" = { filename = "yargs-unparser-npm-2.0.0-930f3ff3f6-68f9a542c6.zip"; sha512 = "68f9a542c6927c3768c2f16c28f71b19008710abd6b8f8efbac6dcce26bbb68ab6503bed1d5994bdbc2df9a5c87c161110c1dfe04c6a3fe5c6ad1b0e15d9a8a3"; };
"yargs@npm:16.2.0" = { filename = "yargs-npm-16.2.0-547873d425-b14afbb51e.zip"; sha512 = "b14afbb51e3251a204d81937c86a7e9d4bdbf9a2bcee38226c900d00f522969ab675703bee2a6f99f8e20103f608382936034e64d921b74df82b63c07c5e8f59"; };
"ylru@npm:1.3.2" = { filename = "ylru-npm-1.3.2-81969d097f-b6bb393114.zip"; sha512 = "b6bb3931144424114f2350c072cfeb180f205add93509c605ae025cbed8059846f8a5767655feeeab890d288b5b4c4b36f5d5d867ee4e6946c16bcc7ec3ddaee"; };
"yocto-queue@npm:0.1.0" = { filename = "yocto-queue-npm-0.1.0-c6c9a7db29-f77b3d8d00.zip"; sha512 = "f77b3d8d00310def622123df93d4ee654fc6a0096182af8bd60679ddcdfb3474c56c6c7190817c84a2785648cdee9d721c0154eb45698c62176c322fb46fc700"; };
};
isolated."canvas@npm:2.11.0" = optionalOverride (args.overrideCanvasAttrs or null) (mkIsolatedBuild { pname = "canvas"; version = "2.11.0"; reference = "npm:2.11.0"; locators = [
"@gar/promisify@npm:1.1.3"
"@mapbox/node-pre-gyp@npm:1.0.10"
"@npmcli/fs@npm:2.1.2"
"@npmcli/move-file@npm:2.0.1"
"@tootallnate/once@npm:2.0.0"
"abbrev@npm:1.1.1"
"agent-base@npm:6.0.2"
"agentkeepalive@npm:4.2.1"
"aggregate-error@npm:3.1.0"
"ansi-regex@npm:5.0.1"
"aproba@npm:2.0.0"
"are-we-there-yet@npm:2.0.0"
"are-we-there-yet@npm:3.0.1"
"balanced-match@npm:1.0.2"
"brace-expansion@npm:1.1.11"
"brace-expansion@npm:2.0.1"
"cacache@npm:16.1.3"
"canvas@npm:2.11.0"
"chownr@npm:2.0.0"
"clean-stack@npm:2.2.0"
"color-support@npm:1.1.3"
"concat-map@npm:0.0.1"
"console-control-strings@npm:1.1.0"
"debug@npm:4.3.4"
"decompress-response@npm:4.2.1"
"delegates@npm:1.0.0"
"depd@npm:1.1.2"
"detect-libc@npm:2.0.1"
"emoji-regex@npm:8.0.0"
"encoding@npm:0.1.13"
"env-paths@npm:2.2.1"
"err-code@npm:2.0.3"
"fs-minipass@npm:2.1.0"
"fs.realpath@npm:1.0.0"
"gauge@npm:3.0.2"
"gauge@npm:4.0.4"
"glob@npm:7.2.3"
"glob@npm:8.1.0"
"graceful-fs@npm:4.2.10"
"has-unicode@npm:2.0.1"
"http-cache-semantics@npm:4.1.1"
"http-proxy-agent@npm:5.0.0"
"https-proxy-agent@npm:5.0.1"
"humanize-ms@npm:1.2.1"
"iconv-lite@npm:0.6.3"
"imurmurhash@npm:0.1.4"
"indent-string@npm:4.0.0"
"infer-owner@npm:1.0.4"
"inflight@npm:1.0.6"
"inherits@npm:2.0.4"
"ip@npm:2.0.0"
"is-fullwidth-code-point@npm:3.0.0"
"is-lambda@npm:1.0.1"
"isexe@npm:2.0.0"
"lru-cache@npm:6.0.0"
"lru-cache@npm:7.14.1"
"make-dir@npm:3.1.0"
"make-fetch-happen@npm:10.2.1"
"mimic-response@npm:2.1.0"
"minimatch@npm:3.1.2"
"minimatch@npm:5.1.6"
"minipass-collect@npm:1.0.2"
"minipass-fetch@npm:2.1.2"
"minipass-flush@npm:1.0.5"
"minipass-pipeline@npm:1.2.4"
"minipass-sized@npm:1.0.3"
"minipass@npm:3.3.6"
"minipass@npm:4.0.3"
"minizlib@npm:2.1.2"
"mkdirp@npm:1.0.4"
"ms@npm:2.1.2"
"ms@npm:2.1.3"
"nan@npm:2.17.0"
"negotiator@npm:0.6.3"
"node-fetch@npm:2.6.9"
"node-gyp@npm:9.3.1"
"nopt@npm:5.0.0"
"nopt@npm:6.0.0"
"npmlog@npm:5.0.1"
"npmlog@npm:6.0.2"
"object-assign@npm:4.1.1"
"once@npm:1.4.0"
"p-map@npm:4.0.0"
"path-is-absolute@npm:1.0.1"
"promise-inflight@npm:1.0.1"
"promise-retry@npm:2.0.1"
"readable-stream@npm:3.6.0"
"retry@npm:0.12.0"
"rimraf@npm:3.0.2"
"safe-buffer@npm:5.2.1"
"safer-buffer@npm:2.1.2"
"semver@npm:6.3.0"
"semver@npm:7.3.8"
"set-blocking@npm:2.0.0"
"signal-exit@npm:3.0.7"
"simple-concat@npm:1.0.1"
"simple-get@npm:3.1.1"
"smart-buffer@npm:4.2.0"
"socks-proxy-agent@npm:7.0.0"
"socks@npm:2.7.1"
"ssri@npm:9.0.1"
"string-width@npm:4.2.3"
"string_decoder@npm:1.3.0"
"strip-ansi@npm:6.0.1"
"tar@npm:6.1.13"
"tr46@npm:0.0.3"
"unique-filename@npm:2.0.1"
"unique-slug@npm:3.0.0"
"util-deprecate@npm:1.0.2"
"webidl-conversions@npm:3.0.1"
"whatwg-url@npm:5.0.0"
"which@npm:2.0.2"
"wide-align@npm:1.1.5"
"wrappy@npm:1.0.2"
"yallist@npm:4.0.0"
]; });
in overriddenProject
